#######################################################################################################

Executes daly to update all the stock signals 
Current signals -
1. EMA Cross indicator
2. Turn Around Stocks

#######################################################################################################

In [1]:
import os, sys 

# Get repo root (works both locally & on GitHub Actions)
repo_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
src_path = os.path.join(repo_root, "src")

if src_path not in sys.path:
    sys.path.append(src_path)

print("✅ Added to path:", src_path)
print("Current working directory:", os.getcwd())

# Now your imports will work
import get_stocks_data as gs

# from src import __version__
# print(__version__)

✅ Added to path: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\src
Current working directory: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\notebooks

In [2]:
import numpy as np 
import pandas as pd 
import yfinance as yf
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns',120)
import datetime as dt
import datetime
import time 
import ta
import sqlite3

In [3]:
yf.__version__

'1.2.0'

In [4]:
analysis_period = 30 # past 30 days for Analysis
raw_data_needed = analysis_period + 1 * 365  # +1 year of buffer for calculating indicators
output_period = 30 # restrict output file for EMA-signals in 30 days

In [5]:
# Determine repository root
# GitHub sets GITHUB_WORKSPACE; locally, we use current working directory
repo_root = os.environ.get("GITHUB_WORKSPACE", os.getcwd())

# if repo_root == os.getcwd(): #then go one directory above to reach repo root
#     repo_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir))

if "d:\\Work" in repo_root or "D:\\Work" in repo_root:
    repo_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir))

print("Repository root determined as:", repo_root)

# Construct full path to the database
db_path = os.path.join(repo_root, "data", "stocks.db")

# Optional: check if it exists
if not os.path.exists(db_path):
    print(f"ERROR: Database not found at {db_path}")
    sys.exit(1)  # stop execution if DB missing

print("Using database at:", db_path)

# Now you can safely call your function
# Example:
# stocklist = gs.get_company_symbols(db_path, 'COMPANY_DETAILS')

Repository root determined as: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals
Using database at: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\data\stocks.db

In [6]:

import importlib
import get_stocks_data as gs
importlib.reload(gs)

stocklist = gs.get_company_symbols(db_path, 'COMPANY_DETAILS')
stocklist.head()

tickers = list(stocklist.ticker.unique())
print(len(tickers))
# tickers = ["ESSAR?SHPNG.NS","LATENTVIEW.NS","BHEL.NS"]
# tickers = tickers[:500] # for testing, limit to first 10 tickers

stock_df = gs.fetch_stock_data(tickers, raw_data_needed)

stock_df.head()

2026-03-13 10:49:12,405 - INFO - 📈 Fetching data for 2178 tickers...
2026-03-13 10:49:12,412 - INFO - Fetching data from 2025-02-11 to 2026-03-13

d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\data\stocks.db
2178

[                       1%                       ]  24 of 2178 completed2026-03-13 10:49:15,231 - ERROR - $MANGCHEFER.NS: possibly delisted; no price data found  (1d 2025-02-11 10:49:12.407886 -> 2026-03-13 10:49:12.412272) (Yahoo error = "No data found, symbol may be delisted")
[*                      3%                       ]  66 of 2178 completed2026-03-13 10:49:17,475 - ERROR - $IEL.NS: possibly delisted; no price data found  (1d 2025-02-11 10:49:12.407886 -> 2026-03-13 10:49:12.412272) (Yahoo error = "No data found, symbol may be delisted")
[********              17%                       ]  373 of 2178 completed2026-03-13 10:49:31,726 - ERROR - $AARVEEDEN.NS: possibly delisted; no price data found  (1d 2025-02-11 10:49:12.407886 -> 2026-03-13 10:49:12.412272) (Yahoo error = "No data found, symbol may be delisted")
[***********           22%                       ]  487 of 2178 completed2026-03-13 10:49:37,502 - ERROR - $BARBEQUE.NS: possibly delisted; no price data found  (1d 2025-02-11 10:49:12.407886 -> 2026-03-13 10:49:12.412272) (Yahoo error = "No data found, symbol may be delisted")
[*****************     36%                       ]  783 of 2178 completed2026-03-13 10:49:50,351 - ERROR - $WORTH.NS: possibly delisted; no price data found  (1d 2025-02-11 10:49:12.407886 -> 2026-03-13 10:49:12.412272) (Yahoo error = "No data found, symbol may be delisted")
[******************    38%                       ]  828 of 2178 completed2026-03-13 10:49:52,812 - ERROR - $DHANI.NS: possibly delisted; no price data found  (1d 2025-02-11 10:49:12.407886 -> 2026-03-13 10:49:12.412272) (Yahoo error = "No data found, symbol may be delisted")
[********************  42%                       ]  911 of 2178 completed2026-03-13 10:49:56,743 - ERROR - $ACLGATI.NS: possibly delisted; no price data found  (1d 2025-02-11 10:49:12.407886 -> 2026-03-13 10:49:12.412272) (Yahoo error = "No data found, symbol may be delisted")
[**********************57%**                     ]  1248 of 2178 completed2026-03-13 10:50:11,717 - ERROR - $ROLTA.NS: possibly delisted; no price data found  (1d 2025-02-11 10:49:12.407886 -> 2026-03-13 10:49:12.412272) (Yahoo error = "No data found, symbol may be delisted")
[**********************61%****                   ]  1336 of 2178 completed2026-03-13 10:50:15,618 - ERROR - $TATAMOTORS.NS: possibly delisted; no price data found  (1d 2025-02-11 10:49:12.407886 -> 2026-03-13 10:49:12.412272) (Yahoo error = "No data found, symbol may be delisted")
[**********************70%*********              ]  1528 of 2178 completed2026-03-13 10:50:24,076 - ERROR - $SUNDARMHLD.NS: possibly delisted; no price data found  (1d 2025-02-11 10:49:12.407886 -> 2026-03-13 10:49:12.412272) (Yahoo error = "No data found, symbol may be delisted")
[**********************76%***********            ]  1650 of 2178 completed2026-03-13 10:50:29,757 - ERROR - $NDTV-RE.NS: possibly delisted; no price data found  (1d 2025-02-11 10:49:12.407886 -> 2026-03-13 10:49:12.412272) (Yahoo error = "No data found, symbol may be delisted")
[**********************78%************           ]  1693 of 2178 completed2026-03-13 10:50:31,867 - ERROR - $SMSLIFE.NS: possibly delisted; no price data found  (1d 2025-02-11 10:49:12.407886 -> 2026-03-13 10:49:12.412272) (Yahoo error = "No data found, symbol may be delisted")
[**********************88%*****************      ]  1914 of 2178 completed2026-03-13 10:50:41,553 - ERROR - $SMLISUZU.NS: possibly delisted; no price data found  (1d 2025-02-11 10:49:12.407886 -> 2026-03-13 10:49:12.412272) (Yahoo error = "No data found, symbol may be delisted")
[**********************91%*******************    ]  1975 of 2178 completed2026-03-13 10:50:44,633 - ERROR - $CREATIVE.NS: possibly delisted; no price data found  (1d 2025-02-11 10:49:12.407886 -> 2026-03-13 10:49:12.412272) (Yahoo error = "No data found, symbol may be delisted")
[**********************91%*******************    ]  1984 of 2178 completed2026-03-13 10:50:45,332 - ERROR - $GODHA.NS: possibly delisted; no price data found  (1d 2025-02-11 10:49:12.407886 -> 2026-03-13 10:49:12.412272) (Yahoo error = "No data found, symbol may be delisted")
[**********************93%********************   ]  2016 of 2178 completed2026-03-13 10:50:47,177 - ERROR - $JCHAC.NS: possibly delisted; no price data found  (1d 2025-02-11 10:49:12.407886 -> 2026-03-13 10:49:12.412272) (Yahoo error = "No data found, symbol may be delisted")
[*********************100%***********************]  2178 of 2178 completed
2026-03-13 10:50:54,075 - ERROR -
17 Failed downloads:
2026-03-13 10:50:54,076 - ERROR - ['MANGCHEFER.NS', 'IEL.NS', 'AARVEEDEN.NS', 'BARBEQUE.NS', 'WORTH.NS', 'DHANI.NS', 'ACLGATI.NS', 'ROLTA.NS', 'TATAMOTORS.NS', 'SUNDARMHLD.NS', 'NDTV-RE.NS', 'SMSLIFE.NS', 'SMLISUZU.NS', 'CREATIVE.NS', 'GODHA.NS', 'JCHAC.NS']: possibly delisted; no price data found  (1d 2025-02-11 10:49:12.407886 -> 2026-03-13 10:49:12.412272) (Yahoo error = "No data found, symbol may be delisted")
2026-03-13 10:50:54,077 - ERROR - ['RECLTD.NS']: TypeError("'NoneType' object is not subscriptable")
2026-03-13 10:50:56,832 - INFO - ✅ Download completed in 104.42 seconds
2026-03-13 10:51:01,183 - INFO - 📊 Final dataset: 567,731 rows from 2025-02-11 to 2026-03-13

Price,Date,Ticker,Adj Close,Close,High,Low,Open,Volume,20ema,50ema,100ema,200ema,30dv,7dv,Symbol
0,2025-02-11,20MICRONS.NS,NaN,167.662796,177.189777,166.657342,175.646743,207691.0,167.662796,167.662796,167.662796,167.662796,NaN,NaN,20MICRONS
1,2025-02-12,20MICRONS.NS,NaN,170.370575,176.144502,157.488749,170.231205,203986.0,167.920680,167.768983,167.716415,167.689739,NaN,NaN,20MICRONS
2,2025-02-13,20MICRONS.NS,NaN,172.749817,177.976213,169.245638,170.679167,112430.0,168.380598,167.964310,167.816087,167.740088,NaN,NaN,20MICRONS
3,2025-02-14,20MICRONS.NS,NaN,169.623947,173.257531,164.616563,172.033065,151387.0,168.499012,168.029394,167.851886,167.758833,NaN,NaN,20MICRONS
4,2025-02-17,20MICRONS.NS,NaN,169.842957,172.799605,163.879881,165.502558,89141.0,168.627007,168.100514,167.891313,167.779571,NaN,NaN,20MICRONS

In [7]:
stock_df.tail()

Price,Date,Ticker,Adj Close,Close,High,Low,Open,Volume,20ema,50ema,100ema,200ema,30dv,7dv,Symbol
567726,2026-03-06,ZYDUSWELL.NS,NaN,381.200012,386.600006,380.000000,381.000000,67849.0,396.232687,412.982075,423.200938,418.182594,166976.533333,136866.714286,ZYDUSWELL
567727,2026-03-09,ZYDUSWELL.NS,NaN,373.500000,376.000000,367.950012,374.000000,134200.0,394.067669,411.433758,422.216761,417.737991,168010.866667,143552.571429,ZYDUSWELL
567728,2026-03-10,ZYDUSWELL.NS,NaN,378.649994,381.450012,374.250000,376.500000,65082.0,392.599319,410.148121,421.354053,417.349056,167738.866667,129586.142857,ZYDUSWELL
567729,2026-03-11,ZYDUSWELL.NS,NaN,384.299988,389.799988,378.649994,378.649994,69641.0,391.808907,409.134468,420.620309,417.020209,163944.300000,102681.857143,ZYDUSWELL
567730,2026-03-12,ZYDUSWELL.NS,NaN,388.899994,390.649994,376.899994,388.600006,63154.0,391.531867,408.340960,419.992184,416.740406,162366.100000,87048.857143,ZYDUSWELL

##### Call Accumulation signal

In [8]:
import importlib
import accumulation_signal as acs
importlib.reload(acs)

# Detect accumulation
accumulation_df = acs.detect_gradual_accumulation(stock_df)
print("Total accumulation signals detected:", len(accumulation_df))

# Filter the ones meeting entry criteria
accum_df = acs.filter_accumulation(accumulation_df)
print("Total accumulation signals entry:", len(accum_df))


status  = acs.save_accumulation_to_db(accum_df, db_path)
if status:
    print("✅ Database updated successfully")
else:
    print("⚠️ Database Update failed")
# View
accum_df.head()

Total accumulation signals detected: 2161
          Symbol      AD_Slope  Above_20EMA_%  Avg_Volume_Spike    RSI  \
117   ANANDRATHI  2.715561e+04           95.0              0.96  57.23
537        EBGNG  6.605004e+04           95.0              0.72  54.80
1047   KIRLOSENG  9.442712e+04          100.0              1.32  58.80
2104         VTL  3.545306e+05          100.0              0.63  62.25
1806    SPECTRUM  1.172993e+03           95.0              1.24  57.47
272          BEL  1.667333e+06           95.0              1.05  60.35
904    INOXINDIA  4.624278e+03           80.0              1.12  58.18
274      BELRISE  5.028598e+05          100.0              1.05  56.05
57      AEROFLEX  9.120310e+05          100.0              0.98  55.64
451   DATAPATTNS  1.441209e+05          100.0              1.12  70.31

      Accumulating
117           True
537           True
1047          True
2104          True
1806          True
272           True
904           True
274           True
57            True
451           True
Total accumulation signals entry: 5
✅ Database updated successfully

,Symbol,Date,AD_Slope,Above_20EMA_%,Avg_Volume_Spike,RSI,Accumulating,20ema,50ema,200ema,Close,7dv,30dv
0,APOLLOPIPE,2026-03-13,641168.3199,100.0,2.14,73.39,True,361.140906,331.372145,340.362771,412.899994,1.214166e+07,3.250557e+06
1,BALRAMCHIN,2026-03-12,458996.6078,100.0,1.47,68.02,True,478.253696,460.512886,475.694810,509.299988,2.171173e+06,7.760655e+05
2,DWARKESH,2026-03-12,358007.3509,80.0,1.44,63.66,True,37.660506,37.145084,39.798202,38.830002,2.249767e+06,9.903524e+05
3,TATAPOWER,2026-03-12,653835.3789,80.0,1.34,72.96,True,378.148329,375.780421,378.974030,402.149994,8.980429e+06,4.935179e+06
4,TIRUPATIFL,2026-03-12,63799.0937,85.0,1.20,74.23,True,38.041706,36.730789,37.321211,44.070000,8.549271e+05,5.357272e+05

In [9]:
accumulation_df.head(20)

,Symbol,Date,AD_Slope,Above_20EMA_%,Avg_Volume_Spike,RSI,Accumulating,20ema,50ema,200ema,Close,7dv,30dv
117,ANANDRATHI,2026-03-12,2.715561e+04,95.0,0.96,57.23,True,3089.290478,3047.648657,2776.246749,3075.100098,1.746687e+05,1.682972e+05
537,EBGNG,2026-03-13,6.605004e+04,95.0,0.72,54.80,True,355.260650,333.347294,326.820998,377.700012,2.160214e+05,2.831103e+05
1047,KIRLOSENG,2026-03-12,9.442712e+04,100.0,1.32,58.80,True,1401.584068,1306.447888,1081.574763,1468.900024,5.372707e+05,6.001325e+05
2104,VTL,2026-03-12,3.545306e+05,100.0,0.63,62.25,True,527.065103,493.521502,454.860237,541.349976,2.698503e+05,1.013548e+06
1806,SPECTRUM,2026-03-13,1.172993e+03,95.0,1.24,57.47,True,1370.119842,1313.961880,1392.601469,1407.599976,2.951857e+03,2.750133e+03
272,BEL,2026-03-12,1.667333e+06,95.0,1.05,60.35,True,447.458134,434.070342,396.755986,453.549988,2.468182e+07,1.958285e+07
904,INOXINDIA,2026-03-13,4.624278e+03,80.0,1.12,58.18,True,1161.599182,1149.914648,1134.502995,1168.599976,6.497429e+04,5.485927e+04
274,BELRISE,2026-03-12,5.028598e+05,100.0,1.05,56.05,True,187.094552,180.269091,153.859293,188.080002,7.412668e+06,5.747264e+06
57,AEROFLEX,2026-03-12,9.120310e+05,100.0,0.98,55.64,True,218.043585,203.816473,190.892218,237.130005,1.850284e+06,3.665490e+06
451,DATAPATTNS,2026-03-12,1.441209e+05,100.0,1.12,70.31,True,3159.047456,2929.653465,2664.785878,3332.000000,1.562234e+06,1.132267e+06
1340,NITIRAJ,2026-03-13,3.587506e+03,90.0,1.35,62.33,True,207.670959,198.220506,202.217428,217.000000,7.351857e+03,6.648567e+03
1968,TORNTPHARM,2026-03-12,6.529837e+04,100.0,1.13,71.18,True,4301.811781,4128.813595,3737.139920,4446.000000,3.730416e+05,3.993268e+05
619,FINPIPE,2026-03-12,9.460259e+04,80.0,1.19,51.20,True,184.220963,181.755578,186.266144,188.309998,7.018403e+05,7.958468e+05
1144,MACPOWER,2026-03-12,1.804442e+03,85.0,0.64,51.89,True,932.341910,924.486971,930.990426,928.400024,2.044114e+04,3.293227e+04
1732,SHILPAMED,2026-03-12,2.653435e+04,95.0,0.75,52.07,True,327.152632,323.015520,348.995350,332.299988,4.606776e+05,5.093479e+05
1688,SCHAEFFLER,2026-03-12,3.486981e+04,80.0,1.49,55.92,True,4074.836761,3966.138792,3856.593424,3988.600098,8.903843e+04,1.260760e+05
1644,SAILIFE,2026-03-12,1.856509e+05,100.0,0.86,62.35,True,976.748987,934.440077,863.827885,1008.849976,7.675621e+05,8.134629e+05
615,FINCABLES,2026-03-12,3.336311e+05,100.0,1.64,61.19,True,872.976258,825.016610,824.150544,894.450012,8.865671e+05,6.698658e+05
2066,VHLTD,2026-03-13,1.318064e+03,90.0,0.89,58.45,True,144.646093,141.031738,128.650730,144.600006,1.743629e+04,1.559703e+04
1950,TIINDIA,2026-03-12,2.384765e+05,85.0,0.78,53.73,True,2604.068416,2575.431436,2745.514621,2549.699951,4.485234e+05,7.086900e+05

#### EMA Signal indicator

In [10]:
import importlib
import ema_signal as emasignal
importlib.reload(emasignal)

# Detect Golden/Death cross with volume confirmation

long_stocks, short_stocks, ema_df = emasignal.generate_ema_signals(
    stock_df,
    analysis_period=15,
    vol_thresh=1.5,
    output_period=30
)
long_stocks.head()


status  = emasignal.save_EMA_signal_to_db(long_stocks, db_path)
if status:
    print("✅ Database updated successfully")
else:
    print("⚠️ Database Update failed")
# View
ema_df.head()

98 tickers with Close/200ema crossover between 2026-02-26–2026-03-13
25 tickers with 50ema/200ema crossover between 2026-02-26–2026-03-13
✅ Metadata fetched for 120 total stocks
✅ Final signals: 74 long | 73 short
✅ Saved 74 new EMA signal records to SIGNAL_EMA_CROSS
📦 Table now has 4371 total records.
✅ Database updated successfully

,Symbol,signal_1,Date_1,Price_1,7dratio_1,30dratio_1,Vol1,Mom1,signal_2,Date_2,Price_2,7dratio_2,30dratio_2,Vol2,Mom2,currentPrice,Capitalization,MCap,upFrom52wlow,PE,PB,PBXPE,debtToEquity,PS,PricetoCash,EPS,CashperShare,update date,beta,AD,AD_50
0,360ONE,Price_lt_200ema,2026-03-02,1075.0,2.13,0.77,2.13,-6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1029.0,Large Cap,41768.0,0.49,36.0,4.0,161.0,1.47,9.88,32.573527,28.0,32.0,2026-03-13,0.24,NaN,NaN
1,A2ZINFRA,Price_lt_200ema,2026-03-04,16.0,0.37,2.70,2.70,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,Nano Cap,283.0,0.34,115.0,6.0,683.0,3.54,0.73,59.007353,0.0,0.0,2026-03-13,0.06,NaN,NaN
3,AADHARHFC,Price_gt_200ema,2026-03-09,482.0,2.30,1.37,2.30,-2.0,Death cross,2026-03-02,453.0,0.44,1.67,1.67,-10.0,461.0,Large Cap,20020.0,0.41,20.0,3.0,57.0,2.55,9.34,11.133266,23.0,41.0,2026-03-13,0.00,0.81,0.25
5,ABINFRA,Price_lt_200ema,2026-03-12,17.0,2.99,0.47,2.99,-3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,Small Cap,1078.0,0.58,46.0,7.0,316.0,0.58,4.42,24.845361,0.0,1.0,2026-03-13,0.64,NaN,NaN
6,ACMESOLAR,Price_gt_200ema,2026-03-12,240.0,2.33,0.79,2.33,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,256.0,Mid Cap,15537.0,0.55,32.0,3.0,104.0,2.72,7.92,4.573182,8.0,56.0,2026-03-13,0.00,NaN,NaN

##### Update the Stock returns table

In [11]:
ema_df

,Symbol,signal_1,Date_1,Price_1,7dratio_1,30dratio_1,Vol1,Mom1,signal_2,Date_2,Price_2,7dratio_2,30dratio_2,Vol2,Mom2,currentPrice,Capitalization,MCap,upFrom52wlow,PE,PB,PBXPE,debtToEquity,PS,PricetoCash,EPS,CashperShare,update date,beta,AD,AD_50
0,360ONE,Price_lt_200ema,2026-03-02,1075.0,2.13,0.77,2.13,-6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1029.0,Large Cap,41768.0,0.49,36.0,4.0,161.0,1.47,9.88,32.573527,28.0,32.0,2026-03-13,0.24,NaN,NaN
1,A2ZINFRA,Price_lt_200ema,2026-03-04,16.0,0.37,2.70,2.70,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,Nano Cap,283.0,0.34,115.0,6.0,683.0,3.54,0.73,59.007353,0.0,0.0,2026-03-13,0.06,NaN,NaN
3,AADHARHFC,Price_gt_200ema,2026-03-09,482.0,2.30,1.37,2.30,-2.0,Death cross,2026-03-02,453.0,0.44,1.67,1.67,-10.0,461.0,Large Cap,20020.0,0.41,20.0,3.0,57.0,2.55,9.34,11.133266,23.0,41.0,2026-03-13,0.00,0.81,0.25
5,ABINFRA,Price_lt_200ema,2026-03-12,17.0,2.99,0.47,2.99,-3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,Small Cap,1078.0,0.58,46.0,7.0,316.0,0.58,4.42,24.845361,0.0,1.0,2026-03-13,0.64,NaN,NaN
6,ACMESOLAR,Price_gt_200ema,2026-03-12,240.0,2.33,0.79,2.33,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,256.0,Mid Cap,15537.0,0.55,32.0,3.0,104.0,2.72,7.92,4.573182,8.0,56.0,2026-03-13,0.00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,XTGLOBAL,Price_gt_200ema,2026-03-05,37.0,1.01,3.74,3.74,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.0,Nano Cap,457.0,0.42,52.0,2.0,126.0,0.26,1.25,18.798236,1.0,2.0,2026-03-13,0.49,NaN,NaN
153,XTGLOBAL,Price_lt_200ema,2026-03-04,34.0,0.47,3.63,3.63,-5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.0,Nano Cap,457.0,0.42,52.0,2.0,126.0,0.26,1.25,18.798236,1.0,2.0,2026-03-13,0.49,NaN,NaN
154,XTGLOBAL,Price_gt_200ema,2026-02-27,39.0,6.14,3.38,6.14,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.0,Nano Cap,457.0,0.42,52.0,2.0,126.0,0.26,1.25,18.798236,1.0,2.0,2026-03-13,0.49,NaN,NaN
155,ZENTEC,Price_lt_200ema,2026-03-11,1409.0,0.48,2.15,2.15,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1395.0,Mid Cap,12550.0,0.18,47.0,7.0,332.0,0.01,15.04,15.06203,29.0,93.0,2026-03-13,-0.34,NaN,NaN
156,ZENTEC,Price_gt_200ema,2026-03-09,1441.0,0.69,2.06,2.06,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1395.0,Mid Cap,12550.0,0.18,47.0,7.0,332.0,0.01,15.04,15.06203,29.0,93.0,2026-03-13,-0.34,NaN,NaN

In [13]:
# Update the signal returns 
# import accumulation_signal as acs

import importlib
import signal_returns as sigret
# importlib.reload(sigret)

# from signal_returns import generate_signal_returns

status, final_returns = sigret.generate_signal_returns(db_path, stock_df)

if status:
    print("✅ Signal returns generation successful!")
    display(final_returns.head())
else:
    print("❌ Signal returns generation failed.")

✅ Total signals loaded: 2425
✅ Total signals after merging: 413659
📦 Existing SIGNAL_RETURNS records: 2967
✅ New unique records found: 0
ℹ️ No new records to save — SIGNAL_RETURNS already up to date.
🔒 Database connection closed.
✅ Signal returns generation successful!

Empty DataFrame
Columns: [Symbol, Signal_Type, Signal_date, Signal_Price, Signal_Rank, ret_1w, ret_1w_price, ret_1w_date, ret_2w, ret_2w_price, ret_2w_date, ret_1m, ret_1m_price, ret_1m_date, ret_3m, ret_3m_price, ret_3m_date, ret_6m, ret_6m_price, ret_6m_date, ret_1y, ret_1y_price, ret_1y_date, ret_sinceSignal, current_price, current_date, ret_1w_perc, ret_2w_perc, ret_1m_perc, ret_3m_perc, ret_6m_perc, ret_1y_perc, ret_sinceSignal_perc]
Index: []