#######################################################################################################

Executes daly to update all the stock signals 
Current signals -
1. EMA Cross indicator
2. Turn Around Stocks

#######################################################################################################

In [1]:
import os, sys 

# Get repo root (works both locally & on GitHub Actions)
repo_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
src_path = os.path.join(repo_root, "src")

if src_path not in sys.path:
    sys.path.append(src_path)

print("✅ Added to path:", src_path)
print("Current working directory:", os.getcwd())

# Now your imports will work
import get_stocks_data as gs

# from src import __version__
# print(__version__)

✅ Added to path: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\src
Current working directory: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\notebooks

In [2]:
import numpy as np 
import pandas as pd 
import yfinance as yf
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns',120)
import datetime as dt
import datetime
import time 
import ta
import sqlite3
# print(yf.__version__, pd.__version__)

In [3]:
# Determine repository root
# GitHub sets GITHUB_WORKSPACE; locally, we use current working directory
repo_root = os.environ.get("GITHUB_WORKSPACE", os.getcwd())

# if repo_root == os.getcwd(): #then go one directory above to reach repo root
#     repo_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir))

if "d:\\Work" in repo_root or "D:\\Work" in repo_root:
    repo_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir))

print("Repository root determined as:", repo_root)

# Construct full path to the database
db_path = os.path.join(repo_root, "data", "stocks.db")

# Optional: check if it exists
if not os.path.exists(db_path):
    print(f"ERROR: Database not found at {db_path}")
    sys.exit(1)  # stop execution if DB missing

print("Using database at:", db_path)

# Now you can safely call your function
# Example:
# stocklist = gs.get_company_symbols(db_path, 'STOCK_DETAILS')

Repository root determined as: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals
Using database at: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\data\stocks.db

##### Define Signal Generation parameters

In [4]:
analysis_period = 15 # past 15 days for Analysis in EMA signal generation
raw_data_needed = analysis_period + 2.6 * 365  # +1 year of buffer for calculating indicators
output_period = 30 # restrict output file for EMA-signals in 30 days

In [5]:

import importlib
import get_stocks_data as gs
importlib.reload(gs)

stocklist = gs.get_company_symbols(db_path, 'STOCK_DETAILS')
stocklist.head()

tickers = list(stocklist.ticker.unique())
print(len(tickers))
# tickers = ["ESSARSHPNG.NS","LATENTVIEW.NS","BHEL.NS"]
# tickers = tickers[:500] # for testing, limit to first 10 tickers

stock_df = gs.fetch_stock_data(tickers, raw_data_needed)

# Update STOCK_PRICS table  for all stocks in STOCK_DETAILS table with latest stock prices.
stock_df_latest = stock_df[stock_df['Date'] == stock_df['Date'].max()]
gs.update_current_stock_prices(db_path, stock_df_latest)

stock_df.head()

2026-04-19 10:44:18,437 - INFO - 📈 Fetching data for 2265 tickers...
2026-04-19 10:44:18,445 - INFO - Fetching data from 2023-08-29 to 2026-04-19

d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\data\stocks.db
2265

[*********************100%***********************]  2265 of 2265 completed
2026-04-19 10:46:49,863 - INFO - ✅ Download completed in 151.43 seconds
2026-04-19 10:46:56,831 - INFO - 📊 Final dataset: 1,316,813 rows from 2023-08-29 to 2026-04-17
2026-04-19 10:46:56,896 - INFO - 🔄 Updating STOCK_PRICES table with latest stock prices...
2026-04-19 10:46:58,011 - INFO - ✅ STOCK_PRICES table updated successfully.
2026-04-19 10:46:58,015 - INFO - 📊 STOCK_PRICES table updated for : 2026-04-17

Price,Date,Ticker,Close,High,Low,Open,Volume,20ema,50ema,100ema,200ema,30dv,7dv,Symbol
0,2023-08-29,20MICRONS.NS,115.370781,118.092957,115.370781,115.370781,34273.0,115.370781,115.370781,115.370781,115.370781,NaN,NaN,20MICRONS
1,2023-08-30,20MICRONS.NS,113.588989,116.806107,113.094048,113.588989,24863.0,115.201086,115.300907,115.335498,115.353052,NaN,NaN,20MICRONS
2,2023-08-31,20MICRONS.NS,114.380905,114.727362,114.380905,114.380905,22371.0,115.122974,115.264828,115.316595,115.343379,NaN,NaN,20MICRONS
3,2023-09-01,20MICRONS.NS,113.836464,114.380902,113.836464,113.836464,8642.0,115.000449,115.208814,115.287286,115.328384,NaN,NaN,20MICRONS
4,2023-09-04,20MICRONS.NS,119.528282,119.528282,114.034433,119.478785,92700.0,115.431671,115.378205,115.371266,115.370174,NaN,NaN,20MICRONS

##### Call Accumulation signal

In [6]:
import importlib
import accumulation_signal as acs
importlib.reload(acs)

# Detect accumulation
accumulation_df = acs.detect_gradual_accumulation(stock_df)
print("Total accumulation signals detected:", len(accumulation_df))

# Filter the ones meeting entry criteria
accum_df = acs.filter_accumulation(accumulation_df)
print("Total accumulation signals entry:", len(accum_df))


status  = acs.save_accumulation_to_db(accum_df, db_path)
if status:
    print("✅ Database updated successfully")
else:
    print("⚠️ Database Update failed")
# View
accum_df.head()

Total accumulation signals detected: 2244
Total accumulation signals entry: 6
✅ Database updated successfully

,Symbol,Date,AD_Slope,Above_20EMA_%,Avg_Volume_Spike,RSI,Accumulating,20ema,50ema,200ema,Close,7dv,30dv
0,IITL,2026-04-17,1.311376e+04,85.0,1.76,80.24,True,143.183320,140.698894,167.269944,165.250000,1.046653e+05,4.178880e+04
1,PAISALO,2026-04-17,3.316186e+06,95.0,1.61,90.40,True,38.104087,36.201936,36.243983,43.810001,1.717585e+07,8.484986e+06
2,WSTCSTPAPR,2026-04-17,3.412694e+04,85.0,1.40,71.03,True,448.890685,431.275281,447.356463,495.049988,1.539850e+05,9.960910e+04
3,SAATVIKGL,2026-04-17,1.399619e+05,85.0,1.39,86.38,True,419.973340,401.384254,416.824434,472.250000,5.075900e+05,2.336450e+05
4,GRPLTD,2026-04-17,3.300524e+02,90.0,1.36,64.11,True,1917.247408,1853.948382,2033.912357,1971.800049,4.337429e+03,2.863833e+03

#### EMA Signal indicator

In [7]:
import importlib
import ema_signal as emasignal
importlib.reload(emasignal)

# Detect Golden/Death cross with volume confirmation

long_stocks, short_stocks, ema_df = emasignal.generate_ema_signals(
    stock_df,
    analysis_period= analysis_period,
    vol_thresh=1.5,
    output_period= output_period
)
long_stocks.head()


status  = emasignal.save_EMA_signal_to_db(long_stocks, db_path)
if status:
    print("✅ Database updated successfully")
else:
    print("⚠️ Database Update failed")
# View
ema_df.head()

174 tickers with Close/200ema crossover between 2026-04-04–2026-04-19
16 tickers with 50ema/200ema crossover between 2026-04-04–2026-04-19
✅ Metadata fetched for 187 total stocks
✅ Final signals: 159 long | 14 short
✅ Saved 159 new EMA signal records to SIGNAL_EMA_CROSS
📦 Table now has 4560 total records.
✅ Database updated successfully

,Symbol,signal_1,Date_1,Price_1,7dratio_1,30dratio_1,Vol1,Mom1,signal_2,Date_2,Price_2,7dratio_2,30dratio_2,Vol2,Mom2,currentPrice,Capitalization,MCap,upFrom52wlow,PE,PB,PBXPE,debtToEquity,PS,PricetoCash,EPS,CashperShare,update date,beta,AD,AD_50
1,ABDL,Price_gt_200ema,2026-04-10,509.0,3.01,1.32,3.01,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,574.0,Mid Cap,16050.0,0.69,60.0,11.0,636.0,0.67,4.18,102.008889,10.0,6.0,2026-04-19,0.00,NaN,NaN
2,ADANIGREEN,Price_gt_200ema,2026-04-08,1030.0,2.15,1.90,2.15,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1127.0,Large Cap,185686.0,0.88,132.0,10.0,1296.0,2.96,14.69,30.615681,9.0,37.0,2026-04-19,0.80,NaN,NaN
3,ADANIPORTS,Price_gt_200ema,2026-04-08,1453.0,2.19,1.21,2.19,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1573.0,Large Cap,362505.0,0.97,27.0,5.0,138.0,0.82,9.94,30.748485,58.0,51.0,2026-04-19,0.33,NaN,NaN
4,ADFFOODS,Price_gt_200ema,2026-04-17,227.0,5.56,2.31,5.56,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,227.0,Small Cap,2493.0,0.50,31.0,5.0,146.0,0.11,3.86,25.524688,7.0,9.0,2026-04-19,0.21,NaN,NaN
5,AEQUS,Price_gt_200ema,2026-04-10,144.0,4.13,1.62,4.13,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171.0,Mid Cap,11202.0,0.94,0.0,13.0,0.0,1.08,10.07,165.595353,-1.0,1.0,2026-04-19,0.00,NaN,NaN

##### Update the Stock returns table

In [13]:
# Update the signal returns 
# import accumulation_signal as acs

import importlib
import signal_returns as sigret
importlib.reload(sigret)

# from signal_returns import generate_signal_returns

status, final_returns = sigret.generate_signal_returns(db_path, stock_df)

if status:
    print("✅ Signal returns generation successful!")
    display(final_returns.head())
else:
    print("❌ Signal returns generation failed.")

✅ Total signals Present: 2627
✅ Total rows after merging signals with future prices: 560210
✅ Total signals after merging for updated Signal Price: 560210
✅ Total records after return calculation: 2583
✅ Total records after return calculation: 2583
💾 SIGNAL_RETURNS table replaced successfully with new data.
🔒 Database connection closed.
✅ Signal returns generation successful!

,Symbol,Signal_Type,Signal_date,Updated_Signal_Price,Signal_Rank,ret_1w,ret_1w_price,ret_1w_date,ret_1w_max,ret_1w_max_price,ret_1w_max_date,ret_1w_dd,ret_1w_dd_price,ret_1w_dd_date,ret_1w_time_to_peak,ret_1w_time_to_dd,ret_1w_peak_to_end,ret_1w_pct_days_profit,ret_1w_volatility,ret_2w,ret_2w_price,ret_2w_date,ret_2w_max,ret_2w_max_price,ret_2w_max_date,ret_2w_dd,ret_2w_dd_price,ret_2w_dd_date,ret_2w_time_to_peak,ret_2w_time_to_dd,ret_2w_peak_to_end,ret_2w_pct_days_profit,ret_2w_volatility,ret_1m,ret_1m_price,ret_1m_date,ret_1m_max,ret_1m_max_price,ret_1m_max_date,ret_1m_dd,ret_1m_dd_price,ret_1m_dd_date,ret_1m_time_to_peak,ret_1m_time_to_dd,ret_1m_peak_to_end,ret_1m_pct_days_profit,ret_1m_volatility,ret_3m,ret_3m_price,ret_3m_date,ret_3m_max,ret_3m_max_price,ret_3m_max_date,ret_3m_dd,ret_3m_dd_price,ret_3m_dd_date,ret_3m_time_to_peak,ret_3m_time_to_dd,ret_3m_peak_to_end,ret_3m_pct_days_profit,ret_3m_volatility,ret_6m,ret_6m_price,ret_6m_date,ret_6m_max,ret_6m_max_price,ret_6m_max_date,ret_6m_dd,ret_6m_dd_price,ret_6m_dd_date,ret_6m_time_to_peak,ret_6m_time_to_dd,ret_6m_peak_to_end,ret_6m_pct_days_profit,ret_6m_volatility,ret_1y,ret_1y_price,ret_1y_date,ret_1y_max,ret_1y_max_price,ret_1y_max_date,ret_1y_dd,ret_1y_dd_price,ret_1y_dd_date,ret_1y_time_to_peak,ret_1y_time_to_dd,ret_1y_peak_to_end,ret_1y_pct_days_profit,ret_1y_volatility,ret_sinceSignal_max,ret_sinceSignal_max_price,ret_sinceSignal_max_date,ret_sinceSignal_dd,ret_sinceSignal_dd_price,ret_sinceSignal_dd_date,ret_sinceSignal,current_price,current_date,Signal_Price,ret_1w_perc,ret_2w_perc,ret_1m_perc,ret_3m_perc,ret_6m_perc,ret_1y_perc,ret_sinceSignal_perc
0,20MICRONS,Golden cross,2025-07-17,253.863495,4,6.49,270.329987,2025-07-24,9.03,276.779999,2025-07-23,1.38,257.357697,2025-07-21,6.0,4.0,-2.54,1.0,0.03,-7.64,234.470001,2025-07-31,9.03,276.779999,2025-07-23,-7.64,234.470001,2025-07-31,6.0,14.0,-16.67,0.6,0.06,-10.42,227.399994,2025-08-18,9.03,276.779999,2025-07-23,-9.93,228.649994,2025-08-14,6.0,28.0,-18.96,0.30,0.06,-14.93,215.960007,2025-10-15,9.03,276.779999,2025-07-23,-18.40,207.160004,2025-09-30,6.0,75.0,-23.96,0.10,0.06,-24.90,190.639999,2026-01-13,9.03,276.779999,2025-07-23,-27.06,185.160004,2025-11-24,6.0,130.0,-33.93,0.05,0.08,NaN,NaN,None,9.03,276.779999,2025-07-23,-47.55,133.139999,2026-03-30,6.0,256.0,-36.51,0.03,0.11,9.03,276.779999,2025-07-23,-47.55,133.139999,2026-03-30,-27.48,184.089996,2026-04-17,254.0,6.49,-7.64,-10.42,-14.93,-24.9,None,-27.48
1,20MICRONS,Golden cross,2025-07-16,258.582184,2,7.04,276.779999,2025-07-23,7.04,276.779999,2025-07-23,-1.82,253.863495,2025-07-17,7.0,1.0,0.00,0.6,0.04,-5.31,244.850006,2025-07-30,7.04,276.779999,2025-07-23,-7.39,239.470001,2025-07-28,7.0,12.0,-12.35,0.5,0.05,-12.06,227.399994,2025-08-18,7.04,276.779999,2025-07-23,-11.58,228.649994,2025-08-14,7.0,29.0,-18.61,0.24,0.06,-17.05,214.500000,2025-10-14,7.04,276.779999,2025-07-23,-19.89,207.160004,2025-09-30,7.0,76.0,-24.09,0.08,0.06,-25.41,192.880005,2026-01-12,7.04,276.779999,2025-07-23,-28.39,185.160004,2025-11-24,7.0,131.0,-32.45,0.04,0.08,NaN,NaN,None,7.04,276.779999,2025-07-23,-48.51,133.139999,2026-03-30,7.0,257.0,-35.85,0.03,0.11,7.04,276.779999,2025-07-23,-48.51,133.139999,2026-03-30,-28.81,184.089996,2026-04-17,259.0,7.04,-5.31,-12.06,-17.05,-25.41,None,-28.81
2,20MICRONS,Golden cross,2025-06-17,235.924515,6,-3.68,227.243713,2025-06-24,-1.69,231.932541,2025-06-18,-5.94,221.907822,2025-06-23,1.0,6.0,-1.99,0.0,0.02,-2.13,230.897217,2025-07-01,-1.69,231.932541,2025-06-18,-5.94,221.907822,2025-06-23,1.0,6.0,-0.44,0.0,0.02,7.60,253.863495,2025-07-17,9.60,258.582184,2025-07-16,-6.85,219.757523,2025-07-09,29.0,22.0,-2.00,0.09,0.04,-4.52,225.270004,2025-09-15,17.32,276.779999,2025-07-23,-6.85,219.757523,2025-07-09,36.0,22.0,-21.83,0.24,0.06,-18.36,192.610001,2025-12-15,17.32,276.779999,2025-07-23,-21.52,185.160004,2025-11-24,36.0,160.0,-36.57,0.12,0.08,NaN,NaN,None,17.32,276.779999,2025-07-23,-43.57,133.139999,2026-03-30,36.0,286.0,-39.29,0.07,0.12,17.32,276.779999,2025-07-23,-43.57,133.139999,2026-03-30,-21.97,184.089996,2026-04-17,237.0,-3.68,-2.13,7.6,-4.52,-18.36,None,-21.97
3,360ONE,Golden cross,2025-06-12,1075.927856,5,3.05,1108.760864,2025-06-19,8.16,1163.681396,2025-06-16,3.05,1108.760864,2025-06-19,4.0,7.0,-5.10,1.0,0.02,7.72,1158.955444,2025-06-26,10.04,1183.978271,2025-06-25,3.05,1108.760864,2025-06-19,13.0,7.0,-2.33,1.0,0.02,9.88,1182.187256,2025-07-14,15.87,1246.659424,2025-07-07,3.05,1108.760864,2025-06-19,25.0,7.0,-5.46,1.00,0.04,-0.31,1072.544922,2025-09-10,15.87,1246.659424,2025-07-07,-5.85,1012.948059,2025-08-29,25.0,78.0,-16.18,0.56,0.06,3.90,1117.900024,2025-12-09,15.87,1246.659424,2025-07-07,-7.36,996.730591,2025-09-26,25.0,106.0,-11.97,0.61,0.06,NaN,NaN,None,15.87,1246.659424,2025-07-07,-13.63,929.250000,2026-04-07,25.0,299.0,-12.39,0.64,0.06,15.87,1246.659424,2025-07-07,-13.63,929.250000,2026-04-07,3.47,1113.300049,2026-04-17,1081.0,3.05,7.72,9.88,-0.31,3.9,None,3.47
4,3MINDIA,Accumulation,2025-08-07,32000.000000,4,-5.16,30350.000000,2025-08-14,-1.20,31615.000000,2025-08-08,-5.16,30350.000000,2025-08-14,1.0,7.0,-3.95,0.0,0.02,-3.52,30875.000000,2025-08-21,-1.20,31615.000000,2025-08-08,-5.16,30350.000000,2025-08-14,1.0,7.0,-2.31,0.0,0.01,-3.64,30835.000000,2025-09-08,-1.20,31615.000000,2025-08-08,-5.16,30350.000000,2025-08-14,1.0,7.0,-3.84,0.00,0.01,11.84,35790.000000,2025-11-06,12.14,35885.000000,2025-11-04,-9.89,28835.000000,2025-09-29,89.0,53.0,0.00,0.02,0.03,9.45,35025.000000,2026-02-03,13.70,36385.000000,2026-01-05,-9.89,28835.000000,2025-09-29,151.0,53.0,-4.25,0.52,0.08,NaN,NaN,None,17.61,37635.000000,2026-02-10,-9.89,28835.000000,2025-09-29,187.0,53.0,-19.45,0.56,0.08,17.61,37635.000000,2026-02-10,-9.89,28835.000000,2025-09-29,-1.84,31410.000000,2026-04-17,32000.0,-5.16,-3.52,-3.64,11.84,9.45,None,-1.84