#######################################################################################################

Executes daly to update all the stock signals 
Current signals -
1. EMA Cross indicator
2. Turn Around Stocks

#######################################################################################################

In [15]:
import os, sys 

# Get repo root (works both locally & on GitHub Actions)
repo_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
src_path = os.path.join(repo_root, "src")

if src_path not in sys.path:
    sys.path.append(src_path)

print("✅ Added to path:", src_path)
print("Current working directory:", os.getcwd())

# Now your imports will work
import get_stocks_data as gs

# from src import __version__
# print(__version__)

✅ Added to path: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\src
Current working directory: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\notebooks

In [16]:
import numpy as np 
import pandas as pd 
import yfinance as yf
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns',120)
import datetime as dt
import datetime
import time 
import ta
import sqlite3

In [17]:
print(yf.__version__, pd.__version__)

1.2.0 2.2.2

In [18]:
analysis_period = 30 # past 30 days for Analysis
raw_data_needed = analysis_period + 1 * 365  # +1 year of buffer for calculating indicators
output_period = 30 # restrict output file for EMA-signals in 30 days

In [19]:
# Determine repository root
# GitHub sets GITHUB_WORKSPACE; locally, we use current working directory
repo_root = os.environ.get("GITHUB_WORKSPACE", os.getcwd())

# if repo_root == os.getcwd(): #then go one directory above to reach repo root
#     repo_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir))

if "d:\\Work" in repo_root or "D:\\Work" in repo_root:
    repo_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir))

print("Repository root determined as:", repo_root)

# Construct full path to the database
db_path = os.path.join(repo_root, "data", "stocks.db")

# Optional: check if it exists
if not os.path.exists(db_path):
    print(f"ERROR: Database not found at {db_path}")
    sys.exit(1)  # stop execution if DB missing

print("Using database at:", db_path)

# Now you can safely call your function
# Example:
# stocklist = gs.get_company_symbols(db_path, 'STOCK_DETAILS')

Repository root determined as: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals
Using database at: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\data\stocks.db

In [20]:

import importlib
import get_stocks_data as gs
importlib.reload(gs)

stocklist = gs.get_company_symbols(db_path, 'STOCK_DETAILS')
stocklist.head()

tickers = list(stocklist.ticker.unique())
print(len(tickers))
# tickers = ["ESSARSHPNG.NS","LATENTVIEW.NS","BHEL.NS"]
# tickers = tickers[:500] # for testing, limit to first 10 tickers

stock_df = gs.fetch_stock_data(tickers, raw_data_needed)

# Update STOCK_PRICS table  for all stocks in STOCK_DETAILS table with latest stock prices.
stock_df_latest = stock_df[stock_df['Date'] == stock_df['Date'].max()]
gs.update_current_stock_prices(db_path, stock_df_latest)

stock_df.head()

d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\data\stocks.db

2026-04-14 14:56:57,443 - INFO - 📈 Fetching data for 2265 tickers...
2026-04-14 14:56:57,447 - INFO - Fetching data from 2025-03-15 to 2026-04-14

2265

[*********************100%***********************]  2265 of 2265 completed
2026-04-14 15:00:09,689 - INFO - ✅ Download completed in 192.24 seconds
2026-04-14 15:00:13,560 - INFO - 📊 Final dataset: 569,746 rows from 2025-03-17 to 2026-04-13
2026-04-14 15:00:13,588 - INFO - 🔄 Updating STOCK_PRICES table with latest stock prices...
2026-04-14 15:00:14,132 - INFO - ✅ STOCK_PRICES table updated successfully.
2026-04-14 15:00:14,132 - INFO - 📊 STOCK_PRICES table updated for : 2026-04-13

Price,Date,Ticker,Close,High,Low,Open,Volume,20ema,50ema,100ema,200ema,30dv,7dv,Symbol
0,2025-03-17,20MICRONS.NS,186.338440,194.392079,185.263309,193.127785,65883.0,186.338440,186.338440,186.338440,186.338440,NaN,NaN,20MICRONS
1,2025-03-18,20MICRONS.NS,186.338440,186.338440,186.338440,186.338440,0.0,186.338440,186.338440,186.338440,186.338440,NaN,NaN,20MICRONS
2,2025-03-19,20MICRONS.NS,200.245636,213.037869,197.109804,198.105308,147127.0,187.662935,186.883820,186.613830,186.476820,NaN,NaN,20MICRONS
3,2025-03-20,20MICRONS.NS,200.205826,204.028558,199.518926,201.091824,75022.0,188.857496,187.406252,186.882978,186.613427,NaN,NaN,20MICRONS
4,2025-03-21,20MICRONS.NS,203.262009,204.785144,200.584116,201.738889,68420.0,190.229354,188.028046,187.207316,186.779085,NaN,NaN,20MICRONS

##### Call Accumulation signal

In [21]:
import importlib
import accumulation_signal as acs
importlib.reload(acs)

# Detect accumulation
accumulation_df = acs.detect_gradual_accumulation(stock_df)
print("Total accumulation signals detected:", len(accumulation_df))

# Filter the ones meeting entry criteria
accum_df = acs.filter_accumulation(accumulation_df)
print("Total accumulation signals entry:", len(accum_df))


status  = acs.save_accumulation_to_db(accum_df, db_path)
if status:
    print("✅ Database updated successfully")
else:
    print("⚠️ Database Update failed")
# View
accum_df.head()

Total accumulation signals detected: 2241
Total accumulation signals entry: 1
✅ Database updated successfully

,Symbol,Date,AD_Slope,Above_20EMA_%,Avg_Volume_Spike,RSI,Accumulating,20ema,50ema,200ema,Close,7dv,30dv
0,GANECOS,2026-04-13,912265.3748,80.0,2.46,70.26,True,941.154862,868.421381,1018.945866,1049.150024,4.188511e+06,1597730.7

#### EMA Signal indicator

In [22]:
import importlib
import ema_signal as emasignal
importlib.reload(emasignal)

# Detect Golden/Death cross with volume confirmation

long_stocks, short_stocks, ema_df = emasignal.generate_ema_signals(
    stock_df,
    analysis_period=15,
    vol_thresh=1.5,
    output_period=30
)
long_stocks.head()


status  = emasignal.save_EMA_signal_to_db(long_stocks, db_path)
if status:
    print("✅ Database updated successfully")
else:
    print("⚠️ Database Update failed")
# View
ema_df.head()

119 tickers with Close/200ema crossover between 2026-03-30–2026-04-14
13 tickers with 50ema/200ema crossover between 2026-03-30–2026-04-14
✅ Metadata fetched for 131 total stocks
✅ Final signals: 104 long | 16 short
✅ Saved 104 new EMA signal records to SIGNAL_EMA_CROSS
📦 Table now has 4504 total records.
✅ Database updated successfully

,Symbol,signal_1,Date_1,Price_1,7dratio_1,30dratio_1,Vol1,Mom1,signal_2,Date_2,Price_2,7dratio_2,30dratio_2,Vol2,Mom2,currentPrice,Capitalization,MCap,upFrom52wlow,PE,PB,PBXPE,debtToEquity,PS,PricetoCash,EPS,CashperShare,update date,beta,AD,AD_50
0,ABDL,Price_gt_200ema,2026-04-10,509.0,3.01,1.32,3.01,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,500.0,Mid Cap,13983.0,0.52,52.0,9.0,484.0,0.67,3.64,88.871111,10.0,6.0,2026-04-14,0.00,NaN,NaN
1,ACMESOLAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Golden cross,2026-04-06,280.0,0.68,1.7,1.7,22.0,284.0,Mid Cap,17193.0,0.69,35.0,4.0,128.0,2.72,8.76,5.06635,8.0,56.0,2026-04-14,0.00,0.43,0.89
2,ADANIGREEN,Price_gt_200ema,2026-04-08,1030.0,2.15,1.90,2.15,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1085.0,Large Cap,178793.0,0.78,127.0,9.0,1200.0,2.96,14.15,29.479102,9.0,37.0,2026-04-14,0.80,NaN,NaN
3,ADANIPORTS,Price_gt_200ema,2026-04-08,1453.0,2.19,1.21,2.19,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1465.0,Large Cap,337599.0,0.71,25.0,5.0,120.0,0.82,9.25,28.635919,58.0,51.0,2026-04-14,0.33,NaN,NaN
4,AEQUS,Price_gt_200ema,2026-04-10,144.0,4.13,1.62,4.13,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,151.0,Mid Cap,9907.0,0.73,0.0,11.0,0.0,1.08,8.90,146.447241,-1.0,1.0,2026-04-14,0.00,NaN,NaN

##### Update the Stock returns table

In [23]:
conn = sqlite3.connect(db_path)

In [24]:
# Update the signal returns 
# import accumulation_signal as acs

import importlib
import signal_returns as sigret
importlib.reload(sigret)

# from signal_returns import generate_signal_returns

status, final_returns = sigret.generate_signal_returns(db_path, stock_df)

if status:
    print("✅ Signal returns generation successful!")
    display(final_returns.head())
else:
    print("❌ Signal returns generation failed.")

✅ Total signals Present: 2582
✅ Total signals after merging for updated Signal Price: 2582
✅ Total records after return calculation: 2582
💾 SIGNAL_RETURNS table replaced successfully with new data.
🔒 Database connection closed.
✅ Signal returns generation successful!

,Symbol,Signal_Type,Signal_date,Signal_Price,Updated_Signal_Price,Signal_Rank,ret_1w,ret_1w_price,ret_1w_date,ret_2w,ret_2w_price,ret_2w_date,ret_1m,ret_1m_price,ret_1m_date,ret_3m,ret_3m_price,ret_3m_date,ret_6m,ret_6m_price,ret_6m_date,ret_1y,ret_1y_price,ret_1y_date,ret_sinceSignal,current_price,current_date
0,GANECOS,Accumulation,2026-04-13,1049.150024,1049.150024,1,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,0.00,1049.150024,2026-04-13 00:00:00
1,WELCORP,Golden cross,2026-04-13,1006.000000,1006.000000,1,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,-0.05,1005.500000,2026-04-13 00:00:00
2,SPLPETRO,Golden cross,2026-04-13,728.000000,728.000000,2,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,-0.04,727.700012,2026-04-13 00:00:00
3,GANECOS,Accumulation,2026-04-10,1045.750000,1045.750000,1,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,0.33,1049.150024,2026-04-13 00:00:00
4,PAISALO,Golden cross,2026-04-10,39.000000,39.000000,1,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,1.13,39.439999,2026-04-13 00:00:00