#######################################################################################################

Executes daly to update all the stock signals 
Current signals -
1. EMA Cross indicator
2. Turn Around Stocks

#######################################################################################################

In [1]:
import os, sys 

# Get repo root (works both locally & on GitHub Actions)
repo_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
src_path = os.path.join(repo_root, "src")

if src_path not in sys.path:
    sys.path.append(src_path)

print("✅ Added to path:", src_path)
print("Current working directory:", os.getcwd())

# Now your imports will work
import get_stocks_data as gs

# from src import __version__
# print(__version__)

✅ Added to path: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\src
Current working directory: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\notebooks

In [2]:
import numpy as np 
import pandas as pd 
import yfinance as yf
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns',120)
import datetime as dt
import datetime
import time 
import ta
import sqlite3

In [3]:
print(yf.__version__, pd.__version__)

1.2.0 2.2.2

In [4]:
analysis_period = 30 # past 30 days for Analysis
raw_data_needed = analysis_period + 1 * 365  # +1 year of buffer for calculating indicators
output_period = 30 # restrict output file for EMA-signals in 30 days

In [5]:
# Determine repository root
# GitHub sets GITHUB_WORKSPACE; locally, we use current working directory
repo_root = os.environ.get("GITHUB_WORKSPACE", os.getcwd())

# if repo_root == os.getcwd(): #then go one directory above to reach repo root
#     repo_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir))

if "d:\\Work" in repo_root or "D:\\Work" in repo_root:
    repo_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir))

print("Repository root determined as:", repo_root)

# Construct full path to the database
db_path = os.path.join(repo_root, "data", "stocks.db")

# Optional: check if it exists
if not os.path.exists(db_path):
    print(f"ERROR: Database not found at {db_path}")
    sys.exit(1)  # stop execution if DB missing

print("Using database at:", db_path)

# Now you can safely call your function
# Example:
# stocklist = gs.get_company_symbols(db_path, 'STOCK_DETAILS')

Repository root determined as: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals
Using database at: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\data\stocks.db

In [ ]:

import importlib
import get_stocks_data as gs
importlib.reload(gs)

stocklist = gs.get_company_symbols(db_path, 'STOCK_DETAILS')
stocklist.head()

tickers = list(stocklist.ticker.unique())
print(len(tickers))
# tickers = ["ESSAR?SHPNG.NS","LATENTVIEW.NS","BHEL.NS"]
# tickers = tickers[:500] # for testing, limit to first 10 tickers

stock_df = gs.fetch_stock_data(tickers, raw_data_needed)

# Update STOCK_PRICS table  for all stocks in STOCK_DETAILS table with latest stock prices.
stock_df_latest = stock_df[stock_df['Date'] == stock_df['Date'].max()]
gs.update_current_stock_prices(db_path, stock_df_latest)

stock_df.head()

2026-04-04 22:15:43,634 - INFO - 📈 Fetching data for 2300 tickers...
2026-04-04 22:15:43,637 - INFO - Fetching data from 2025-03-05 to 2026-04-04

d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\data\stocks.db
2300

[***                    6%                       ]  141 of 2300 completed2026-04-04 22:15:51,163 - ERROR - $SMSLIFE.NS: possibly delisted; no price data found  (1d 2025-03-05 22:15:43.635980 -> 2026-04-04 22:15:43.635980) (Yahoo error = "No data found, symbol may be delisted")
[*******               15%                       ]  340 of 2300 completed2026-04-04 22:16:00,619 - ERROR - $DHANI.NS: possibly delisted; no price data found  (1d 2025-03-05 22:15:43.635980 -> 2026-04-04 22:15:43.635980) (Yahoo error = "No data found, symbol may be delisted")
[********              17%                       ]  396 of 2300 completed2026-04-04 22:16:03,412 - ERROR - $CREATIVE.NS: possibly delisted; no price data found  (1d 2025-03-05 22:15:43.635980 -> 2026-04-04 22:15:43.635980) (Yahoo error = "No data found, symbol may be delisted")
[********              17%                       ]  397 of 2300 completed2026-04-04 22:16:03,422 - ERROR - $SGLTL.NS: possibly delisted; no price data found  (1d 2025-03-05 22:15:43.635980 -> 2026-04-04 22:15:43.635980) (Yahoo error = "No data found, symbol may be delisted")
[***********           23%                       ]  529 of 2300 completed2026-04-04 22:16:09,602 - ERROR - $NDTV-RE.NS: possibly delisted; no price data found  (1d 2025-03-05 22:15:43.635980 -> 2026-04-04 22:15:43.635980) (Yahoo error = "No data found, symbol may be delisted")
[*****************     36%                       ]  832 of 2300 completed2026-04-04 22:16:23,373 - ERROR - $GODHA.NS: possibly delisted; no price data found  (1d 2025-03-05 22:15:43.635980 -> 2026-04-04 22:15:43.635980) (Yahoo error = "No data found, symbol may be delisted")
[******************    38%                       ]  863 of 2300 completed2026-04-04 22:16:25,426 - ERROR - HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: NIMBSPROJ.NS"}}}
[******************    38%                       ]  867 of 2300 completed2026-04-04 22:16:25,655 - ERROR - $NIMBSPROJ.NS: possibly delisted; no timezone found
[******************    38%                       ]  880 of 2300 completed2026-04-04 22:16:26,489 - ERROR - $IEL.NS: possibly delisted; no price data found  (1d 2025-03-05 22:15:43.635980 -> 2026-04-04 22:15:43.635980) (Yahoo error = "No data found, symbol may be delisted")
[******************    38%                       ]  882 of 2300 completed2026-04-04 22:16:26,517 - ERROR - $SUNDARMHLD.NS: possibly delisted; no price data found  (1d 2025-03-05 22:15:43.635980 -> 2026-04-04 22:15:43.635980) (Yahoo error = "No data found, symbol may be delisted")
[********************  41%                       ]  937 of 2300 completed2026-04-04 22:16:29,187 - ERROR - $ACLGATI.NS: possibly delisted; no price data found  (1d 2025-03-05 22:15:43.635980 -> 2026-04-04 22:15:43.635980) (Yahoo error = "No data found, symbol may be delisted")
[**********************45%                       ]  1029 of 2300 completed2026-04-04 22:16:33,652 - ERROR - $WORTH.NS: possibly delisted; no price data found  (1d 2025-03-05 22:15:43.635980 -> 2026-04-04 22:15:43.635980) (Yahoo error = "No data found, symbol may be delisted")
[**********************47%                       ]  1073 of 2300 completed2026-04-04 22:16:35,912 - ERROR - $JCHAC.NS: possibly delisted; no price data found  (1d 2025-03-05 22:15:43.635980 -> 2026-04-04 22:15:43.635980) (Yahoo error = "No data found, symbol may be delisted")
[**********************58%***                    ]  1332 of 2300 completed2026-04-04 22:16:47,443 - ERROR - $AARVEEDEN.NS: possibly delisted; no price data found  (1d 2025-03-05 22:15:43.635980 -> 2026-04-04 22:15:43.635980) (Yahoo error = "No data found, symbol may be delisted")
[**********************70%*********              ]  1620 of 2300 completed2026-04-04 22:17:00,569 - ERROR - $SEQUENT.NS: possibly delisted; no price data found  (1d 2025-03-05 22:15:43.635980 -> 2026-04-04 22:15:43.635980) (Yahoo error = "No data found, symbol may be delisted")
[**********************82%**************         ]  1877 of 2300 completed2026-04-04 22:17:12,815 - ERROR - $BARBEQUE.NS: possibly delisted; no price data found  (1d 2025-03-05 22:15:43.635980 -> 2026-04-04 22:15:43.635980) (Yahoo error = "No data found, symbol may be delisted")
[**********************82%**************         ]  1878 of 2300 completed2026-04-04 22:17:12,829 - ERROR - $ROLTA.NS: possibly delisted; no price data found  (1d 2025-03-05 22:15:43.635980 -> 2026-04-04 22:15:43.635980) (Yahoo error = "No data found, symbol may be delisted")
[**********************85%****************       ]  1964 of 2300 completed2026-04-04 22:17:16,658 - ERROR - $SMLISUZU.NS: possibly delisted; no price data found  (1d 2025-03-05 22:15:43.635980 -> 2026-04-04 22:15:43.635980) (Yahoo error = "No data found, symbol may be delisted")
[**********************88%*****************      ]  2035 of 2300 completed2026-04-04 22:17:20,469 - ERROR - $TATAMOTORS.NS: possibly delisted; no price data found  (1d 2025-03-05 22:15:43.635980 -> 2026-04-04 22:15:43.635980) (Yahoo error = "No data found, symbol may be delisted")
[**********************97%********************** ]  2221 of 2300 completed2026-04-04 22:17:28,980 - ERROR - $MANGCHEFER.NS: possibly delisted; no price data found  (1d 2025-03-05 22:15:43.635980 -> 2026-04-04 22:15:43.635980) (Yahoo error = "No data found, symbol may be delisted")
2026-04-04 22:17:28,987 - ERROR - $HEUBACHIND.NS: possibly delisted; no price data found  (1d 2025-03-05 22:15:43.635980 -> 2026-04-04 22:15:43.635980) (Yahoo error = "No data found, symbol may be delisted")
[*********************100%***********************]  2300 of 2300 completed
2026-04-04 22:17:32,474 - ERROR -
20 Failed downloads:
2026-04-04 22:17:32,475 - ERROR - ['SMSLIFE.NS', 'DHANI.NS', 'CREATIVE.NS', 'SGLTL.NS', 'NDTV-RE.NS', 'GODHA.NS', 'IEL.NS', 'SUNDARMHLD.NS', 'ACLGATI.NS', 'WORTH.NS', 'JCHAC.NS', 'AARVEEDEN.NS', 'SEQUENT.NS', 'BARBEQUE.NS', 'ROLTA.NS', 'SMLISUZU.NS', 'TATAMOTORS.NS', 'MANGCHEFER.NS', 'HEUBACHIND.NS']: possibly delisted; no price data found  (1d 2025-03-05 22:15:43.635980 -> 2026-04-04 22:15:43.635980) (Yahoo error = "No data found, symbol may be delisted")
2026-04-04 22:17:32,477 - ERROR - ['NIMBSPROJ.NS']: possibly delisted; no timezone found
2026-04-04 22:17:34,865 - INFO - ✅ Download completed in 111.23 seconds
2026-04-04 22:17:39,238 - INFO - 📊 Final dataset: 575,027 rows from 2025-03-05 to 2026-04-02

Price,Date,Ticker,Adj Close,Close,High,Low,Open,Volume,20ema,50ema,100ema,200ema,30dv,7dv,Symbol
0,2025-03-05,20MICRONS.NS,NaN,183.809875,185.163762,174.999658,175.009623,63556.0,183.809875,183.809875,183.809875,183.809875,NaN,NaN,20MICRONS
1,2025-03-06,20MICRONS.NS,NaN,206.686554,212.440566,184.267813,184.267813,304285.0,185.988607,184.707000,184.262879,184.037504,NaN,NaN,20MICRONS
2,2025-03-07,20MICRONS.NS,NaN,203.411346,209.055853,200.096316,201.091820,137064.0,187.647915,185.440504,184.642057,184.230279,NaN,NaN,20MICRONS
3,2025-03-10,20MICRONS.NS,NaN,203.351624,217.019890,200.096321,202.087329,159993.0,189.143507,186.142901,185.012543,184.420541,NaN,NaN,20MICRONS
4,2025-03-11,20MICRONS.NS,NaN,194.670822,204.078332,193.426442,204.078332,109217.0,189.669918,186.477329,185.203796,184.522534,NaN,NaN,20MICRONS

##### Call Accumulation signal

In [18]:
import importlib
import accumulation_signal as acs
importlib.reload(acs)

# Detect accumulation
accumulation_df = acs.detect_gradual_accumulation(stock_df)
print("Total accumulation signals detected:", len(accumulation_df))

# Filter the ones meeting entry criteria
accum_df = acs.filter_accumulation(accumulation_df)
print("Total accumulation signals entry:", len(accum_df))


status  = acs.save_accumulation_to_db(accum_df, db_path)
if status:
    print("✅ Database updated successfully")
else:
    print("⚠️ Database Update failed")
# View
accum_df.head()

Total accumulation signals detected: 2159
          Symbol     AD_Slope  Above_20EMA_%  Avg_Volume_Spike    RSI  \
943      JAINREC  586254.0041          100.0              1.20  73.36
201   AUROPHARMA  143844.5839          100.0              0.87  61.72
760      HARDWYN  403070.9523           90.0              0.92  89.14
245   BALRAMCHIN  274281.9136           80.0              1.57  51.45
1115  LINDEINDIA   10421.7499           85.0              1.06  54.55
530     DWARKESH  175613.7142           85.0              1.89  69.31
1212    MEGASTAR   16368.3882           85.0              2.00  75.73
666       GESHIP   20004.2015           95.0              1.24  58.13
195   ATLANTAELE   57301.6985           95.0              1.75  69.52
916      IPCALAB   31207.5940           95.0              1.13  74.24

      Accumulating
943           True
201           True
760           True
245           True
1115          True
530           True
1212          True
666           True
195           True
916           True
Total accumulation signals entry: 3
✅ Database updated successfully

,Symbol,Date,AD_Slope,Above_20EMA_%,Avg_Volume_Spike,RSI,Accumulating,20ema,50ema,200ema,Close,7dv,30dv
0,DWARKESH,2026-03-30,175613.7142,85.0,1.89,69.31,True,39.132337,37.951776,39.327568,45.919998,5.649296e+06,2.173875e+06
1,SPECTRUM,2026-03-30,2779.6320,90.0,1.73,69.73,True,1430.707301,1363.276750,1397.186982,1552.800049,1.191271e+04,5.995400e+03
2,SPLPETRO,2026-03-30,7992.6543,80.0,1.59,59.22,True,677.929560,655.303198,667.546155,738.400024,2.725890e+05,1.487257e+05

In [19]:
accumulation_df.head(5)

,Symbol,Date,AD_Slope,Above_20EMA_%,Avg_Volume_Spike,RSI,Accumulating,20ema,50ema,200ema,Close,7dv,30dv
943,JAINREC,2026-03-30,586254.0041,100.0,1.20,73.36,True,432.575189,414.504522,376.517124,456.500000,1.826170e+06,1.315125e+06
201,AUROPHARMA,2026-03-30,143844.5839,100.0,0.87,61.72,True,1268.398857,1230.755698,1170.077681,1304.400024,1.718568e+06,1.776383e+06
760,HARDWYN,2026-03-30,403070.9523,90.0,0.92,89.14,True,18.452335,17.663633,15.831586,20.120001,8.252727e+05,8.297677e+05
245,BALRAMCHIN,2026-03-30,274281.9136,80.0,1.57,51.45,True,484.247759,469.539998,476.686535,497.100006,1.257523e+06,1.005195e+06
1115,LINDEINDIA,2026-03-30,10421.7499,85.0,1.06,54.55,True,6960.382460,6670.898992,6347.198168,6844.000000,9.449571e+04,7.667707e+04

#### EMA Signal indicator

In [20]:
import importlib
import ema_signal as emasignal
importlib.reload(emasignal)

# Detect Golden/Death cross with volume confirmation

long_stocks, short_stocks, ema_df = emasignal.generate_ema_signals(
    stock_df,
    analysis_period=15,
    vol_thresh=1.5,
    output_period=30
)
long_stocks.head()


status  = emasignal.save_EMA_signal_to_db(long_stocks, db_path)
if status:
    print("✅ Database updated successfully")
else:
    print("⚠️ Database Update failed")
# View
ema_df.head()

77 tickers with Close/200ema crossover between 2026-03-16–2026-03-31
35 tickers with 50ema/200ema crossover between 2026-03-16–2026-03-31
✅ Metadata fetched for 109 total stocks
✅ Final signals: 63 long | 56 short
✅ Saved 63 new EMA signal records to SIGNAL_EMA_CROSS
📦 Table now has 4443 total records.
✅ Database updated successfully

,Symbol,signal_1,Date_1,Price_1,7dratio_1,30dratio_1,Vol1,Mom1,signal_2,Date_2,Price_2,7dratio_2,30dratio_2,Vol2,Mom2,currentPrice,Capitalization,MCap,upFrom52wlow,PE,PB,PBXPE,debtToEquity,PS,PricetoCash,EPS,CashperShare,update date,beta,AD,AD_50
0,360ONE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Death cross,2026-03-24,989.0,2.9,0.94,2.9,-21.0,950.0,Large Cap,38567.0,0.33,33.0,4.0,137.0,1.47,9.12,30.063001,29.0,32.0,2026-03-31,0.24,-0.61,-0.43
1,AADHARHFC,Price_lt_200ema,2026-03-19,463.0,2.06,0.73,2.06,-12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,449.0,Mid Cap,19557.0,0.33,19.0,3.0,54.0,2.55,9.12,10.848076,23.0,41.0,2026-03-31,0.00,NaN,NaN
3,ACMESOLAR,Price_lt_200ema,2026-03-23,238.0,0.24,3.07,3.07,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,262.0,Mid Cap,15853.0,0.59,33.0,3.0,108.0,2.72,8.08,4.666108,8.0,56.0,2026-03-31,0.00,NaN,NaN
4,AHLEAST,Price_gt_200ema,2026-03-30,148.0,5.30,0.54,5.30,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,148.0,Nano Cap,263.0,0.56,0.0,1.0,0.0,1.55,2.14,30.085383,-32.0,5.0,2026-03-31,-0.62,NaN,NaN
5,AIAENG,Price_lt_200ema,2026-03-19,3573.0,0.27,2.09,2.09,-16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3637.0,Large Cap,33937.0,0.53,29.0,5.0,135.0,0.14,7.87,6.456538,124.0,563.0,2026-03-31,0.12,NaN,NaN

##### Update the Stock returns table

In [21]:
# Update the signal returns 
# import accumulation_signal as acs

import importlib
import signal_returns as sigret
# importlib.reload(sigret)

# from signal_returns import generate_signal_returns

status, final_returns = sigret.generate_signal_returns(db_path, stock_df)

if status:
    print("✅ Signal returns generation successful!")
    display(final_returns.head())
else:
    print("❌ Signal returns generation failed.")

✅ Total signals loaded: 2548
✅ Total signals after merging: 430007
DEBUG merged_df columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG inside calculate_returns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]
DEBUG group columns: ['Symbol', 'Signal_date', 'Signal_Type', 'Signal_Price', 'Signal_Rank', 'Date', 'Price']
DEBUG group index names: [None]

,Symbol,Signal_Type,Signal_date,Signal_Price,Signal_Rank,ret_1w,ret_1w_price,ret_1w_date,ret_2w,ret_2w_price,ret_2w_date,ret_1m,ret_1m_price,ret_1m_date,ret_3m,ret_3m_price,ret_3m_date,ret_6m,ret_6m_price,ret_6m_date,ret_1y,ret_1y_price,ret_1y_date,ret_sinceSignal,current_price,current_date,ret_1w_perc,ret_2w_perc,ret_1m_perc,ret_3m_perc,ret_6m_perc,ret_1y_perc,ret_sinceSignal_perc
141,APOLLOPIPE,Golden cross,2026-03-19,392.000000,1,9.23,428.200012,2026-03-27,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,5.78,414.649994,2026-03-30,9.23,<NA>,<NA>,<NA>,<NA>,<NA>,5.78
150,ARIES,Golden cross,2026-03-23,350.000000,2,-7.27,324.549988,2026-03-30,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,-7.27,324.549988,2026-03-30,-7.27,<NA>,<NA>,<NA>,<NA>,<NA>,-7.27
253,AVL,Death cross,2026-03-19,452.000000,2,8.23,489.200012,2026-03-27,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,5.77,478.100006,2026-03-30,8.23,<NA>,<NA>,<NA>,<NA>,<NA>,5.77
615,DWARKESH,Accumulation Signal,2026-03-30,45.919998,1,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,0.00,45.919998,2026-03-30,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.00
1502,MEGASTAR,Golden cross,2026-03-24,258.000000,1,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,-1.34,254.550003,2026-03-30,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-1.34