#######################################################################################################

Executes daly to update all the stock signals 
Current signals -
1. EMA Cross indicator
2. Turn Around Stocks

#######################################################################################################

In [3]:
import os, sys 

# Get repo root (works both locally & on GitHub Actions)
repo_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
src_path = os.path.join(repo_root, "src")

if src_path not in sys.path:
    sys.path.append(src_path)

print("✅ Added to path:", src_path)
print("Current working directory:", os.getcwd())

# Now your imports will work
from data import get_stocks_data as gs

# from src import __version__
# print(__version__)

✅ Added to path: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\src
Current working directory: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\notebooks

In [4]:
import numpy as np 
import pandas as pd 
import yfinance as yf
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns',120)
import datetime as dt
import datetime
import time 
import ta
import sqlite3
# print(yf.__version__, pd.__version__)

In [5]:
# Determine repository root
# GitHub sets GITHUB_WORKSPACE; locally, we use current working directory
repo_root = os.environ.get("GITHUB_WORKSPACE", os.getcwd())

# if repo_root == os.getcwd(): #then go one directory above to reach repo root
#     repo_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir))

if "d:\\Work" in repo_root or "D:\\Work" in repo_root:
    repo_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir))

print("Repository root determined as:", repo_root)

# Construct full path to the database
db_path = os.path.join(repo_root, "data", "stocks.db")

# Optional: check if it exists
if not os.path.exists(db_path):
    print(f"ERROR: Database not found at {db_path}")
    sys.exit(1)  # stop execution if DB missing

print("Using database at:", db_path)

# Now you can safely call your function
# Example:
# stocklist = gs.get_company_symbols(db_path, 'STOCK_DETAILS')

Repository root determined as: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals
Using database at: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\data\stocks.db

##### Define Signal Generation parameters

In [6]:
analysis_period = 15 # past 15 days for Analysis in EMA signal generation
raw_data_needed = analysis_period + 2.6 * 365  # +1 year of buffer for calculating indicators
output_period = 30 # restrict output file for EMA-signals in 30 days

In [7]:

import importlib
from data  import get_stocks_data as gs
importlib.reload(gs)

stocklist = gs.get_company_symbols(db_path, 'STOCK_DETAILS')
stocklist.head()

tickers = list(stocklist.ticker.unique())
print(len(tickers))
# tickers = ["ESSARSHPNG.NS","LATENTVIEW.NS","BHEL.NS"]
# tickers = tickers[:500] # for testing, limit to first 10 tickers

stock_df = gs.fetch_stock_data(tickers, raw_data_needed)

# Update STOCK_PRICS table  for all stocks in STOCK_DETAILS table with latest stock prices.
stock_df_latest = stock_df[stock_df['Date'] == stock_df['Date'].max()]
gs.update_current_stock_prices(db_path, stock_df_latest)

stock_df.head()

2026-04-17 12:34:23,843 - INFO - 📈 Fetching data for 2265 tickers...
2026-04-17 12:34:23,848 - INFO - Fetching data from 2023-08-27 to 2026-04-17

d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\data\stocks.db
2265

[*********************100%***********************]  2265 of 2265 completed
2026-04-17 12:36:03,599 - INFO - ✅ Download completed in 99.75 seconds
2026-04-17 12:36:08,450 - INFO - 📊 Final dataset: 1,318,635 rows from 2023-08-28 to 2026-04-17
2026-04-17 12:36:08,481 - INFO - 🔄 Updating STOCK_PRICES table with latest stock prices...
2026-04-17 12:36:08,861 - INFO - ✅ STOCK_PRICES table updated successfully.
2026-04-17 12:36:08,861 - INFO - 📊 STOCK_PRICES table updated for : 2026-04-17

Price,Date,Ticker,Close,High,Low,Open,Volume,20ema,50ema,100ema,200ema,30dv,7dv,Symbol
0,2023-08-28,20MICRONS.NS,115.816231,115.816231,115.816231,115.816231,28306.0,115.816231,115.816231,115.816231,115.816231,NaN,NaN,20MICRONS
1,2023-08-29,20MICRONS.NS,115.370781,118.092957,115.370781,115.370781,34273.0,115.773807,115.798762,115.807410,115.811798,NaN,NaN,20MICRONS
2,2023-08-30,20MICRONS.NS,113.588989,116.806107,113.094048,113.588989,24863.0,115.565729,115.712104,115.763481,115.789681,NaN,NaN,20MICRONS
3,2023-08-31,20MICRONS.NS,114.380898,114.727355,114.380898,114.380898,22371.0,115.452888,115.659900,115.736103,115.775663,NaN,NaN,20MICRONS
4,2023-09-01,20MICRONS.NS,113.836456,114.380895,113.836456,113.836456,8642.0,115.298942,115.588393,115.698486,115.756368,NaN,NaN,20MICRONS

##### Call Accumulation signal

In [9]:
import importlib
from signals import accumulation_signal as acs
importlib.reload(acs)

# Detect accumulation
accumulation_df = acs.detect_gradual_accumulation(stock_df)
print("Total accumulation signals detected:", len(accumulation_df))

# Filter the ones meeting entry criteria
accum_df = acs.filter_accumulation(accumulation_df)
print("Total accumulation signals entry:", len(accum_df))


status  = acs.save_accumulation_to_db(accum_df, db_path)
if status:
    print("✅ Database updated successfully")
else:
    print("⚠️ Database Update failed")
# View
accum_df.head()

Total accumulation signals detected: 2244
Total accumulation signals entry: 4
✅ Database updated successfully

,Symbol,Date,AD_Slope,Above_20EMA_%,Avg_Volume_Spike,RSI,Accumulating,20ema,50ema,200ema,Close,7dv,30dv
0,IITL,2026-04-17,1.338579e+04,85.0,1.72,80.52,True,143.256654,140.729091,167.279293,166.020004,9.845657e+04,4.034010e+04
1,PAISALO,2026-04-17,3.371574e+06,95.0,1.59,92.02,True,38.131706,36.213308,36.248265,44.099998,1.668787e+07,8.371124e+06
2,SAATVIKGL,2026-04-17,1.399059e+05,85.0,1.38,86.36,True,419.949531,401.374451,416.821947,472.000000,4.983426e+05,2.314873e+05
3,HFCL,2026-04-17,3.845355e+06,85.0,1.14,86.67,True,78.656522,73.839621,75.253473,91.919998,5.048946e+07,2.869693e+07

#### EMA Signal indicator

In [10]:
import importlib
from signals import ema_signal as emasignal
importlib.reload(emasignal)

# Detect Golden/Death cross with volume confirmation

long_stocks, short_stocks, ema_df = emasignal.generate_ema_signals(
    stock_df,
    analysis_period= analysis_period,
    vol_thresh=1.5,
    output_period= output_period
)
long_stocks.head()


status  = emasignal.save_EMA_signal_to_db(long_stocks, db_path)
if status:
    print("✅ Database updated successfully")
else:
    print("⚠️ Database Update failed")
# View
ema_df.head()

162 tickers with Close/200ema crossover between 2026-04-02–2026-04-17
16 tickers with 50ema/200ema crossover between 2026-04-02–2026-04-17
✅ Metadata fetched for 174 total stocks
✅ Final signals: 147 long | 13 short
✅ Saved 147 new EMA signal records to SIGNAL_EMA_CROSS
📦 Table now has 4553 total records.
✅ Database updated successfully

,Symbol,signal_1,Date_1,Price_1,7dratio_1,30dratio_1,Vol1,Mom1,signal_2,Date_2,Price_2,7dratio_2,30dratio_2,Vol2,Mom2,currentPrice,Capitalization,MCap,upFrom52wlow,PE,PB,PBXPE,debtToEquity,PS,PricetoCash,EPS,CashperShare,update date,beta,AD,AD_50
1,ABDL,Price_gt_200ema,2026-04-10,509.0,3.01,1.32,3.01,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,561.0,Mid Cap,15704.0,0.66,59.0,10.0,611.0,0.67,4.09,99.813333,10.0,6.0,2026-04-17,0.00,NaN,NaN
2,ADANIGREEN,Price_gt_200ema,2026-04-08,1030.0,2.15,1.90,2.15,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1118.0,Large Cap,184072.0,0.85,130.0,10.0,1266.0,2.96,14.56,30.349529,9.0,37.0,2026-04-17,0.80,NaN,NaN
3,ADANIPORTS,Price_gt_200ema,2026-04-08,1453.0,2.19,1.21,2.19,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1561.0,Large Cap,359625.0,0.94,27.0,5.0,136.0,0.82,9.86,30.504202,58.0,51.0,2026-04-17,0.33,NaN,NaN
4,AEGISLOG,Price_gt_200ema,2026-04-17,714.0,2.36,1.91,2.36,-2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,714.0,Large Cap,25067.0,0.37,33.0,4.0,138.0,0.28,3.37,8.864491,22.0,81.0,2026-04-17,0.61,NaN,NaN
5,AEQUS,Price_gt_200ema,2026-04-10,144.0,4.13,1.62,4.13,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,172.0,Mid Cap,11250.0,0.95,0.0,13.0,0.0,1.08,10.10,166.166505,-1.0,1.0,2026-04-17,0.00,NaN,NaN

##### Update the Stock returns table

In [11]:
# Update the signal returns 
# import accumulation_signal as acs

import importlib
from signals import signal_returns as sigret
importlib.reload(sigret)

# from signal_returns import generate_signal_returns

status, final_returns = sigret.generate_signal_returns(db_path, stock_df)

if status:
    print("✅ Signal returns generation successful!")
    display(final_returns.head())
else:
    print("❌ Signal returns generation failed.")

✅ Total signals Present: 2624
✅ Total rows after merging signals with future prices: 560197
✅ Total signals after merging for updated Signal Price: 560197
✅ Total records after return calculation: 2580
✅ Total records after return calculation: 2580
💾 SIGNAL_RETURNS table replaced successfully with new data.
🔒 Database connection closed.
✅ Signal returns generation successful!

,Symbol,Signal_Type,Signal_date,Signal_Price,Updated_Signal_Price,Signal_Rank,ret_1w,ret_1w_price,ret_1w_date,ret_2w,ret_2w_price,ret_2w_date,ret_1m,ret_1m_price,ret_1m_date,ret_3m,ret_3m_price,ret_3m_date,ret_6m,ret_6m_price,ret_6m_date,ret_1y,ret_1y_price,ret_1y_date,ret_sinceSignal,current_price,current_date,ret_1w_perc,ret_2w_perc,ret_1m_perc,ret_3m_perc,ret_6m_perc,ret_1y_perc,ret_sinceSignal_perc
0,20MICRONS,Golden cross,2025-07-17,254.0,253.863495,4,6.49,270.329987,2025-07-24,-7.64,234.470001,2025-07-31,-10.42,227.399994,2025-08-18,-14.93,215.960007,2025-10-15,-24.90,190.639999,2026-01-13,NaN,NaN,NaT,-28.64,181.149994,2026-04-17,6.49,-7.64,-10.42,-14.93,-24.9,<NA>,-28.64
1,20MICRONS,Golden cross,2025-07-16,259.0,258.582184,2,7.04,276.779999,2025-07-23,-5.31,244.850006,2025-07-30,-12.06,227.399994,2025-08-18,-17.05,214.500000,2025-10-14,-25.41,192.880005,2026-01-12,NaN,NaN,NaT,-29.94,181.149994,2026-04-17,7.04,-5.31,-12.06,-17.05,-25.41,<NA>,-29.94
2,20MICRONS,Golden cross,2025-06-17,237.0,235.924515,6,-3.68,227.243713,2025-06-24,-2.13,230.897217,2025-07-01,7.60,253.863495,2025-07-17,-4.52,225.270004,2025-09-15,-18.36,192.610001,2025-12-15,NaN,NaN,NaT,-23.22,181.149994,2026-04-17,-3.68,-2.13,7.6,-4.52,-18.36,<NA>,-23.22
3,360ONE,Golden cross,2025-06-12,1081.0,1075.927856,5,3.05,1108.760864,2025-06-19,7.72,1158.955444,2025-06-26,9.88,1182.187256,2025-07-14,-0.31,1072.544922,2025-09-10,3.90,1117.900024,2025-12-09,NaN,NaN,NaT,3.30,1111.400024,2026-04-17,3.05,7.72,9.88,-0.31,3.9,<NA>,3.30
4,3MINDIA,Accumulation,2025-08-07,32000.0,32000.000000,4,-5.16,30350.000000,2025-08-14,-3.52,30875.000000,2025-08-21,-3.64,30835.000000,2025-09-08,11.84,35790.000000,2025-11-06,9.45,35025.000000,2026-02-03,NaN,NaN,NaT,-2.30,31265.000000,2026-04-17,-5.16,-3.52,-3.64,11.84,9.45,<NA>,-2.30