#######################################################################################################

Executes daly to update all the stock signals 
Current signals -
1. EMA Cross indicator
2. Turn Around Stocks

#######################################################################################################

In [1]:
import os, sys 

# Get repo root (works both locally & on GitHub Actions)
repo_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
src_path = os.path.join(repo_root, "src")

if src_path not in sys.path:
    sys.path.append(src_path)

print("✅ Added to path:", src_path)
print("Current working directory:", os.getcwd())

# Now your imports will work
import get_stocks_data as gs

# from src import __version__
# print(__version__)

✅ Added to path: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\src
Current working directory: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\notebooks

In [ ]:
import numpy as np 
import pandas as pd 
import yfinance as yf
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns',120)
import datetime as dt
import datetime
import time 
import ta
import sqlite3
# print(yf.__version__, pd.__version__)

In [5]:
# Determine repository root
# GitHub sets GITHUB_WORKSPACE; locally, we use current working directory
repo_root = os.environ.get("GITHUB_WORKSPACE", os.getcwd())

# if repo_root == os.getcwd(): #then go one directory above to reach repo root
#     repo_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir))

if "d:\\Work" in repo_root or "D:\\Work" in repo_root:
    repo_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir))

print("Repository root determined as:", repo_root)

# Construct full path to the database
db_path = os.path.join(repo_root, "data", "stocks.db")

# Optional: check if it exists
if not os.path.exists(db_path):
    print(f"ERROR: Database not found at {db_path}")
    sys.exit(1)  # stop execution if DB missing

print("Using database at:", db_path)

# Now you can safely call your function
# Example:
# stocklist = gs.get_company_symbols(db_path, 'STOCK_DETAILS')

Repository root determined as: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals
Using database at: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\data\stocks.db

##### Define Signal Generation parameters

In [ ]:
analysis_period = 15 # past 30 days for Analysis in EMA signal generation
raw_data_needed = analysis_period + 1 * 365  # +1 year of buffer for calculating indicators
output_period = 30 # restrict output file for EMA-signals in 30 days

In [ ]:

import importlib
import get_stocks_data as gs
importlib.reload(gs)

stocklist = gs.get_company_symbols(db_path, 'STOCK_DETAILS')
stocklist.head()

tickers = list(stocklist.ticker.unique())
print(len(tickers))
# tickers = ["ESSARSHPNG.NS","LATENTVIEW.NS","BHEL.NS"]
# tickers = tickers[:500] # for testing, limit to first 10 tickers

stock_df = gs.fetch_stock_data(tickers, raw_data_needed)

# Update STOCK_PRICS table  for all stocks in STOCK_DETAILS table with latest stock prices.
stock_df_latest = stock_df[stock_df['Date'] == stock_df['Date'].max()]
gs.update_current_stock_prices(db_path, stock_df_latest)

stock_df.head()

2026-04-15 11:32:17,192 - INFO - 📈 Fetching data for 2265 tickers...

2026-04-15 11:32:17,194 - INFO - Fetching data from 2023-07-20 to 2026-04-15

d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\data\stocks.db
2265

[*********************100%***********************]  2265 of 2265 completed
2026-04-15 11:34:02,342 - INFO - ✅ Download completed in 105.16 seconds
2026-04-15 11:34:07,560 - INFO - 📊 Final dataset: 1,351,750 rows from 2023-07-20 to 2026-04-15
2026-04-15 11:34:07,606 - INFO - 🔄 Updating STOCK_PRICES table with latest stock prices...
2026-04-15 11:34:08,161 - INFO - ✅ STOCK_PRICES table updated successfully.
2026-04-15 11:34:08,161 - INFO - 📊 STOCK_PRICES table updated for : 2026-04-15

Price,Date,Ticker,Close,High,Low,Open,Volume,20ema,50ema,100ema,200ema,30dv,7dv,Symbol
0,2023-07-20,20MICRONS.NS,99.600288,100.288540,97.338877,98.322098,178917.0,99.600288,99.600288,99.600288,99.600288,NaN,NaN,20MICRONS
1,2023-07-21,20MICRONS.NS,99.403633,101.271754,97.584676,100.141049,103337.0,99.581559,99.592576,99.596394,99.598332,NaN,NaN,20MICRONS
2,2023-07-24,20MICRONS.NS,104.368904,104.368904,103.287363,104.368904,156131.0,100.037497,99.779883,99.690899,99.645800,NaN,NaN,20MICRONS
3,2023-07-25,20MICRONS.NS,109.579964,109.579964,106.187855,109.579964,311628.0,100.946303,100.164200,99.886722,99.744647,NaN,NaN,20MICRONS
4,2023-07-26,20MICRONS.NS,115.024315,115.024315,110.173898,115.024315,414594.0,102.287066,100.746950,100.186477,99.896684,NaN,NaN,20MICRONS

##### Call Accumulation signal

In [7]:
import importlib
import accumulation_signal as acs
importlib.reload(acs)

# Detect accumulation
accumulation_df = acs.detect_gradual_accumulation(stock_df)
print("Total accumulation signals detected:", len(accumulation_df))

# Filter the ones meeting entry criteria
accum_df = acs.filter_accumulation(accumulation_df)
print("Total accumulation signals entry:", len(accum_df))


status  = acs.save_accumulation_to_db(accum_df, db_path)
if status:
    print("✅ Database updated successfully")
else:
    print("⚠️ Database Update failed")
# View
accum_df.head()

Total accumulation signals detected: 2240
Total accumulation signals entry: 4
✅ Database updated successfully

,Symbol,Date,AD_Slope,Above_20EMA_%,Avg_Volume_Spike,RSI,Accumulating,20ema,50ema,200ema,Close,7dv,30dv
0,NITCO,2026-04-15,2.034391e+05,90.0,1.95,62.59,True,83.707170,82.224173,95.534504,91.440002,1.452052e+06,9.627659e+05
1,UTLSOLAR,2026-04-15,6.054637e+04,80.0,1.68,76.73,True,210.283350,204.702777,206.204305,236.089996,6.827520e+05,2.895908e+05
2,PAISALO,2026-04-15,2.193255e+06,90.0,1.54,83.41,True,36.705233,35.513365,36.073670,42.320000,1.389900e+07,7.205666e+06
3,HFCL,2026-04-15,1.482703e+06,85.0,1.19,75.07,True,75.820706,72.375039,74.918431,88.720001,4.107004e+07,2.616768e+07

#### EMA Signal indicator

In [ ]:
import importlib
import ema_signal as emasignal
importlib.reload(emasignal)

# Detect Golden/Death cross with volume confirmation

long_stocks, short_stocks, ema_df = emasignal.generate_ema_signals(
    stock_df,
    analysis_period= analysis_period,
    vol_thresh=1.5,
    output_period= output_period
)
long_stocks.head()


status  = emasignal.save_EMA_signal_to_db(long_stocks, db_path)
if status:
    print("✅ Database updated successfully")
else:
    print("⚠️ Database Update failed")
# View
ema_df.head()

110 tickers with Close/200ema crossover between 2026-03-31–2026-04-15
13 tickers with 50ema/200ema crossover between 2026-03-31–2026-04-15
✅ Metadata fetched for 121 total stocks
✅ Final signals: 102 long | 14 short
✅ Saved 102 new EMA signal records to SIGNAL_EMA_CROSS
📦 Table now has 4516 total records.
✅ Database updated successfully

,Symbol,signal_1,Date_1,Price_1,7dratio_1,30dratio_1,Vol1,Mom1,signal_2,Date_2,Price_2,7dratio_2,30dratio_2,Vol2,Mom2,currentPrice,Capitalization,MCap,upFrom52wlow,PE,PB,PBXPE,debtToEquity,PS,PricetoCash,EPS,CashperShare,update date,beta,AD,AD_50
0,ABDL,Price_gt_200ema,2026-04-10,509.0,3.01,1.32,3.01,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,508.0,Mid Cap,14220.0,0.52,53.0,9.0,501.0,0.67,3.71,90.382222,10.0,6.0,2026-04-15,0.00,NaN,NaN
1,ADANIGREEN,Price_gt_200ema,2026-04-08,1030.0,2.15,1.90,2.15,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1102.0,Large Cap,181527.0,0.82,128.0,10.0,1237.0,2.96,14.36,29.929931,9.0,37.0,2026-04-15,0.80,NaN,NaN
2,ADANIPORTS,Price_gt_200ema,2026-04-08,1453.0,2.19,1.21,2.19,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1506.0,Large Cap,347045.0,0.81,26.0,5.0,127.0,0.82,9.51,29.43717,58.0,51.0,2026-04-15,0.33,NaN,NaN
3,AEQUS,Price_gt_200ema,2026-04-10,144.0,4.13,1.62,4.13,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,152.0,Mid Cap,9964.0,0.75,0.0,11.0,0.0,1.08,8.96,147.299129,-1.0,1.0,2026-04-15,0.00,NaN,NaN
5,ANDHRSUGAR,Price_gt_200ema,2026-04-10,80.0,5.24,1.80,5.24,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.0,Small Cap,1171.0,0.91,14.0,1.0,10.0,0.00,0.50,4.352123,6.0,20.0,2026-04-15,0.15,NaN,NaN

##### Update the Stock returns table

In [9]:
# Update the signal returns 
# import accumulation_signal as acs

import importlib
import signal_returns as sigret
importlib.reload(sigret)

# from signal_returns import generate_signal_returns

status, final_returns = sigret.generate_signal_returns(db_path, stock_df)

if status:
    print("✅ Signal returns generation successful!")
    display(final_returns.head())
else:
    print("❌ Signal returns generation failed.")

✅ Total signals Present: 2594
✅ Total rows after merging signals with future prices: 554902
✅ Total signals after merging for updated Signal Price: 554902
✅ Total records after return calculation: 2550
✅ Total records after return calculation: 2550
💾 SIGNAL_RETURNS table replaced successfully with new data.
🔒 Database connection closed.
✅ Signal returns generation successful!

,Symbol,Signal_Type,Signal_date,Signal_Price,Updated_Signal_Price,Signal_Rank,ret_1w,ret_1w_price,ret_1w_date,ret_2w,ret_2w_price,ret_2w_date,ret_1m,ret_1m_price,ret_1m_date,ret_3m,ret_3m_price,ret_3m_date,ret_6m,ret_6m_price,ret_6m_date,ret_1y,ret_1y_price,ret_1y_date,ret_sinceSignal,current_price,current_date,ret_1w_perc,ret_2w_perc,ret_1m_perc,ret_3m_perc,ret_6m_perc,ret_1y_perc,ret_sinceSignal_perc
0,20MICRONS,Golden cross,2025-07-17,254.0,253.863495,4,6.49,270.329987,2025-07-24,-7.64,234.470001,2025-07-31,-10.42,227.399994,2025-08-18,-14.93,215.960007,2025-10-15,-24.90,190.639999,2026-01-13,NaN,NaN,NaT,-35.03,164.929993,2026-04-15,6.49,-7.64,-10.42,-14.93,-24.9,<NA>,-35.03
1,20MICRONS,Golden cross,2025-07-16,259.0,258.582184,2,7.04,276.779999,2025-07-23,-5.31,244.850006,2025-07-30,-12.06,227.399994,2025-08-18,-17.05,214.500000,2025-10-14,-25.41,192.880005,2026-01-12,NaN,NaN,NaT,-36.22,164.929993,2026-04-15,7.04,-5.31,-12.06,-17.05,-25.41,<NA>,-36.22
2,20MICRONS,Golden cross,2025-06-17,237.0,235.924515,6,-3.68,227.243713,2025-06-24,-2.13,230.897217,2025-07-01,7.60,253.863495,2025-07-17,-4.52,225.270004,2025-09-15,-18.36,192.610001,2025-12-15,NaN,NaN,NaT,-30.09,164.929993,2026-04-15,-3.68,-2.13,7.6,-4.52,-18.36,<NA>,-30.09
3,360ONE,Golden cross,2025-06-12,1081.0,1075.927856,5,3.05,1108.760864,2025-06-19,7.72,1158.955444,2025-06-26,9.88,1182.187256,2025-07-14,-0.31,1072.544922,2025-09-10,3.90,1117.900024,2025-12-09,NaN,NaN,NaT,-1.17,1063.300049,2026-04-15,3.05,7.72,9.88,-0.31,3.9,<NA>,-1.17
4,3MINDIA,Accumulation,2025-08-07,32000.0,32000.000000,4,-5.16,30350.000000,2025-08-14,-3.52,30875.000000,2025-08-21,-3.64,30835.000000,2025-09-08,11.84,35790.000000,2025-11-06,9.45,35025.000000,2026-02-03,NaN,NaN,NaT,-1.25,31600.000000,2026-04-15,-5.16,-3.52,-3.64,11.84,9.45,<NA>,-1.25