#######################################################################################################

Executes daly to update all the stock signals 
Current signals -
1. EMA Cross indicator
2. Turn Around Stocks

#######################################################################################################

In [1]:
import os, sys 

# Get repo root (works both locally & on GitHub Actions)
repo_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
src_path = os.path.join(repo_root, "src")

if src_path not in sys.path:
    sys.path.append(src_path)

print("✅ Added to path:", src_path)
print("Current working directory:", os.getcwd())

# Now your imports will work
import get_stocks_data as gs

# from src import __version__
# print(__version__)

✅ Added to path: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\src
Current working directory: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\notebooks

In [2]:
import numpy as np 
import pandas as pd 
import yfinance as yf
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns',120)
import datetime as dt
import datetime
import time 
import ta
import sqlite3

In [3]:
yf.__version__

'1.2.0'

In [4]:
analysis_period = 30 # past 30 days for Analysis
raw_data_needed = analysis_period + 1 * 365  # +1 year of buffer for calculating indicators
output_period = 30 # restrict output file for EMA-signals in 30 days

In [5]:
# Determine repository root
# GitHub sets GITHUB_WORKSPACE; locally, we use current working directory
repo_root = os.environ.get("GITHUB_WORKSPACE", os.getcwd())

# if repo_root == os.getcwd(): #then go one directory above to reach repo root
#     repo_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir))

if "d:\\Work" in repo_root or "D:\\Work" in repo_root:
    repo_root = os.path.abspath(os.path.join(os.getcwd(), os.pardir))

print("Repository root determined as:", repo_root)

# Construct full path to the database
db_path = os.path.join(repo_root, "data", "stocks.db")

# Optional: check if it exists
if not os.path.exists(db_path):
    print(f"ERROR: Database not found at {db_path}")
    sys.exit(1)  # stop execution if DB missing

print("Using database at:", db_path)

# Now you can safely call your function
# Example:
# stocklist = gs.get_company_symbols(db_path, 'COMPANY_DETAILS')

Repository root determined as: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals
Using database at: d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\data\stocks.db

In [6]:

import importlib
import get_stocks_data as gs
importlib.reload(gs)

stocklist = gs.get_company_symbols(db_path, 'COMPANY_DETAILS')
stocklist.head()

tickers = list(stocklist.ticker.unique())
print(len(tickers))
# tickers = ["ESSAR?SHPNG.NS","LATENTVIEW.NS","BHEL.NS"]
# tickers = tickers[:500] # for testing, limit to first 10 tickers

stock_df = gs.fetch_stock_data(tickers, raw_data_needed)

stock_df.head()

2026-03-17 10:05:28,473 - INFO - 📈 Fetching data for 2178 tickers...
2026-03-17 10:05:28,478 - INFO - Fetching data from 2025-02-15 to 2026-03-17

d:\Work\Projects\Stock_Market\Stock_Market\Stock_signals\Stock-Signals\data\stocks.db
2178

[*                      2%                       ]  35 of 2178 completed2026-03-17 10:05:31,512 - ERROR - $DHANI.NS: possibly delisted; no price data found  (1d 2025-02-15 10:05:28.476538 -> 2026-03-17 10:05:28.478535) (Yahoo error = "No data found, symbol may be delisted")
[*                      3%                       ]  59 of 2178 completed2026-03-17 10:05:32,959 - ERROR - $SMSLIFE.NS: possibly delisted; no price data found  (1d 2025-02-15 10:05:28.476538 -> 2026-03-17 10:05:28.478535) (Yahoo error = "No data found, symbol may be delisted")
[**                     5%                       ]  101 of 2178 completed2026-03-17 10:05:35,116 - ERROR - $NDTV-RE.NS: possibly delisted; no price data found  (1d 2025-02-15 10:05:28.476538 -> 2026-03-17 10:05:28.478535) (Yahoo error = "No data found, symbol may be delisted")
[*******               15%                       ]  316 of 2178 completed2026-03-17 10:05:44,420 - ERROR - $IEL.NS: possibly delisted; no price data found  (1d 2025-02-15 10:05:28.476538 -> 2026-03-17 10:05:28.478535) (Yahoo error = "No data found, symbol may be delisted")
[*********             18%                       ]  398 of 2178 completed2026-03-17 10:05:49,805 - ERROR - $WORTH.NS: possibly delisted; no price data found  (1d 2025-02-15 10:05:28.476538 -> 2026-03-17 10:05:28.478535) (Yahoo error = "No data found, symbol may be delisted")
[***********           22%                       ]  490 of 2178 completed2026-03-17 10:05:54,983 - ERROR - $MANGCHEFER.NS: possibly delisted; no price data found  (1d 2025-02-15 10:05:28.476538 -> 2026-03-17 10:05:28.478535) (Yahoo error = "No data found, symbol may be delisted")
[************          26%                       ]  556 of 2178 completed2026-03-17 10:05:58,428 - ERROR - $GODHA.NS: possibly delisted; no price data found  (1d 2025-02-15 10:05:28.476538 -> 2026-03-17 10:05:28.478535) (Yahoo error = "No data found, symbol may be delisted")
[************          26%                       ]  572 of 2178 completed2026-03-17 10:05:59,350 - ERROR - $BARBEQUE.NS: possibly delisted; no price data found  (1d 2025-02-15 10:05:28.476538 -> 2026-03-17 10:05:28.478535) (Yahoo error = "No data found, symbol may be delisted")
[**************        29%                       ]  640 of 2178 completed2026-03-17 10:06:02,374 - ERROR - $TATAMOTORS.NS: possibly delisted; no price data found  (1d 2025-02-15 10:05:28.476538 -> 2026-03-17 10:05:28.478535) (Yahoo error = "No data found, symbol may be delisted")
[**********************45%                       ]  983 of 2178 completed2026-03-17 10:06:20,451 - ERROR - $ACLGATI.NS: possibly delisted; no price data found  (1d 2025-02-15 10:05:28.476538 -> 2026-03-17 10:05:28.478535) (Yahoo error = "No data found, symbol may be delisted")
[**********************49%                       ]  1078 of 2178 completed2026-03-17 10:06:25,764 - ERROR - $SUNDARMHLD.NS: possibly delisted; no price data found  (1d 2025-02-15 10:05:28.476538 -> 2026-03-17 10:05:28.478535) (Yahoo error = "No data found, symbol may be delisted")
[**********************56%**                     ]  1212 of 2178 completed2026-03-17 10:06:31,491 - ERROR - $AARVEEDEN.NS: possibly delisted; no price data found  (1d 2025-02-15 10:05:28.476538 -> 2026-03-17 10:05:28.478535) (Yahoo error = "No data found, symbol may be delisted")
[**********************63%*****                  ]  1375 of 2178 completed2026-03-17 10:06:38,824 - ERROR - $CREATIVE.NS: possibly delisted; no price data found  (1d 2025-02-15 10:05:28.476538 -> 2026-03-17 10:05:28.478535) (Yahoo error = "No data found, symbol may be delisted")
[**********************66%*******                ]  1441 of 2178 completed2026-03-17 10:06:42,223 - ERROR - $JCHAC.NS: possibly delisted; no price data found  (1d 2025-02-15 10:05:28.476538 -> 2026-03-17 10:05:28.478535) (Yahoo error = "No data found, symbol may be delisted")
[**********************88%*****************      ]  1927 of 2178 completed2026-03-17 10:07:03,612 - ERROR - $ROLTA.NS: possibly delisted; no price data found  (1d 2025-02-15 10:05:28.476538 -> 2026-03-17 10:05:28.478535) (Yahoo error = "No data found, symbol may be delisted")
[**********************92%*******************    ]  2002 of 2178 completed2026-03-17 10:07:07,929 - ERROR - $SMLISUZU.NS: possibly delisted; no price data found  (1d 2025-02-15 10:05:28.476538 -> 2026-03-17 10:05:28.478535) (Yahoo error = "No data found, symbol may be delisted")
[*********************100%***********************]  2178 of 2178 completed
2026-03-17 10:07:15,196 - ERROR -
16 Failed downloads:
2026-03-17 10:07:15,196 - ERROR - ['DHANI.NS', 'SMSLIFE.NS', 'NDTV-RE.NS', 'IEL.NS', 'WORTH.NS', 'MANGCHEFER.NS', 'GODHA.NS', 'BARBEQUE.NS', 'TATAMOTORS.NS', 'ACLGATI.NS', 'SUNDARMHLD.NS', 'AARVEEDEN.NS', 'CREATIVE.NS', 'JCHAC.NS', 'ROLTA.NS', 'SMLISUZU.NS']: possibly delisted; no price data found  (1d 2025-02-15 10:05:28.476538 -> 2026-03-17 10:05:28.478535) (Yahoo error = "No data found, symbol may be delisted")
2026-03-17 10:07:18,288 - INFO - ✅ Download completed in 109.81 seconds
2026-03-17 10:07:22,490 - INFO - 📊 Final dataset: 563,191 rows from 2025-02-17 to 2026-03-17

Price,Date,Ticker,Adj Close,Close,High,Low,Open,Volume,20ema,50ema,100ema,200ema,30dv,7dv,Symbol
0,2025-02-17,20MICRONS.NS,NaN,169.842957,172.799605,163.879881,165.502558,89141.0,169.842957,169.842957,169.842957,169.842957,NaN,NaN,20MICRONS
1,2025-02-18,20MICRONS.NS,NaN,166.916168,170.539802,163.441853,168.469152,80277.0,169.564215,169.728181,169.785000,169.813834,NaN,NaN,20MICRONS
2,2025-02-19,20MICRONS.NS,NaN,179.509308,181.679500,161.281615,165.154125,146902.0,170.511367,170.111754,169.977561,169.910307,NaN,NaN,20MICRONS
3,2025-02-20,20MICRONS.NS,NaN,182.675003,185.940255,176.194277,177.597926,95561.0,171.669808,170.604431,170.228995,170.037319,NaN,NaN,20MICRONS
4,2025-02-21,20MICRONS.NS,NaN,182.565491,188.727663,181.540123,183.172749,120705.0,172.707492,171.073492,170.473282,170.161977,NaN,NaN,20MICRONS

##### Call Accumulation signal

In [8]:
import importlib
import accumulation_signal as acs
importlib.reload(acs)

# Detect accumulation
accumulation_df = acs.detect_gradual_accumulation(stock_df)
print("Total accumulation signals detected:", len(accumulation_df))

# Filter the ones meeting entry criteria
accum_df = acs.filter_accumulation(accumulation_df)
print("Total accumulation signals entry:", len(accum_df))


status  = acs.save_accumulation_to_db(accum_df, db_path)
if status:
    print("✅ Database updated successfully")
else:
    print("⚠️ Database Update failed")
# View
accum_df.head()

Total accumulation signals detected: 2162
         Symbol     AD_Slope  Above_20EMA_%  Avg_Volume_Spike    RSI  \
1422  PASHUPATI    2179.6381          100.0              0.91  68.96
1340    NITIRAJ    3222.6695           95.0              1.37  61.05
1797   SONAMLTD   16110.8247          100.0              1.52  70.50
8      A2ZINFRA  203896.8404           80.0              1.39  53.82
1807   SPECTRUM    1332.3921           95.0              1.30  60.94
0     20MICRONS          NaN           15.0              0.60  14.86
1442        PFS          NaN            0.0              1.08  17.50
1438   PETRONET          NaN           60.0              1.53  41.41
1439        PFC          NaN           80.0              0.83  47.43
1440     PFIZER    -688.3260           50.0              0.38  30.47

      Accumulating
1422          True
1340          True
1797          True
8             True
1807          True
0            False
1442         False
1438         False
1439         False
1440         False
Total accumulation signals entry: 0
✅ Database updated successfully

Empty DataFrame
Columns: [Symbol, Date, AD_Slope, Above_20EMA_%, Avg_Volume_Spike, RSI, Accumulating, 20ema, 50ema, 200ema, Close, 7dv, 30dv]
Index: []

In [ ]:
accumulation_df.head(5)

,Symbol,Date,AD_Slope,Above_20EMA_%,Avg_Volume_Spike,RSI,Accumulating,20ema,50ema,200ema,Close,7dv,30dv
1422,PASHUPATI,2026-03-17,2179.6381,100.0,0.91,68.96,True,967.556583,906.570650,788.614181,998.000000,6.059571e+03,6.418467e+03
1340,NITIRAJ,2026-03-17,3222.6695,95.0,1.37,61.05,True,208.963158,199.131689,208.265298,218.570007,7.211429e+03,6.609433e+03
1797,SONAMLTD,2026-03-17,16110.8247,100.0,1.52,70.50,True,50.756398,46.762849,44.780026,56.220001,1.348547e+05,9.302923e+04
8,A2ZINFRA,2026-03-17,203896.8404,80.0,1.39,53.82,True,15.876609,15.571466,16.486777,15.230000,8.735343e+04,3.621594e+05
1807,SPECTRUM,2026-03-17,1332.3921,95.0,1.30,60.94,True,1387.671696,1323.520350,1401.395001,1502.300049,3.594429e+03,2.785533e+03
0,20MICRONS,2026-03-17,NaN,15.0,0.60,14.86,False,170.719525,179.143141,196.661500,NaN,6.510471e+04,1.064646e+05
1442,PFS,2026-03-17,NaN,0.0,1.08,17.50,False,29.887825,31.512970,34.241508,NaN,7.411819e+05,5.869778e+05
1438,PETRONET,2026-03-17,NaN,60.0,1.53,41.41,False,295.396339,292.387737,283.923038,NaN,6.794931e+06,4.769040e+06
1439,PFC,2026-03-17,NaN,80.0,0.83,47.43,False,406.559712,394.588928,383.302472,NaN,7.736687e+06,9.020762e+06
1440,PFIZER,2026-03-17,-688.3260,50.0,0.38,30.47,False,4838.092872,4878.797946,4900.827765,4734.000000,1.573271e+04,4.967210e+04
1441,PFOCUS,2026-03-17,NaN,85.0,0.63,44.24,False,268.504375,252.297259,196.146920,NaN,3.094695e+06,6.122297e+06
1445,PGHL,2026-03-17,NaN,5.0,0.58,34.86,False,4976.235471,5148.351426,5433.945486,NaN,8.176429e+03,1.748243e+04
1443,PGEL,2026-03-17,-324554.9058,65.0,1.26,33.77,False,571.091187,579.885214,624.115471,521.400024,6.299892e+06,3.341700e+06
1444,PGHH,2026-03-17,NaN,0.0,1.20,17.03,False,11164.836637,11638.707002,12554.936206,NaN,1.412486e+04,7.825967e+03
1446,PGIL,2026-03-17,NaN,5.0,0.43,35.68,False,1534.270007,1553.357585,1482.172131,NaN,3.870857e+04,1.335262e+05
1447,PHOENIXLTD,2026-03-17,NaN,15.0,0.91,25.47,False,1648.197273,1704.210298,1672.578310,NaN,3.796407e+05,4.025227e+05
1448,PICCADIL,2026-03-17,NaN,10.0,1.00,30.19,False,556.951978,573.802444,600.995655,NaN,1.247893e+05,1.604135e+05
1449,PIDILITIND,2026-03-17,NaN,40.0,0.92,27.26,False,1436.613815,1456.315831,1468.918713,NaN,5.617517e+05,7.506344e+05
1437,PERSISTENT,2026-03-17,NaN,0.0,1.01,33.42,False,4979.928235,5432.799586,5662.632367,NaN,6.408829e+05,9.012187e+05
1435,PENIND,2026-03-17,NaN,0.0,1.36,47.24,False,150.271144,166.404463,197.109424,NaN,9.110019e+05,1.144540e+06

#### EMA Signal indicator

In [10]:
import importlib
import ema_signal as emasignal
importlib.reload(emasignal)

# Detect Golden/Death cross with volume confirmation

long_stocks, short_stocks, ema_df = emasignal.generate_ema_signals(
    stock_df,
    analysis_period=15,
    vol_thresh=1.5,
    output_period=30
)
long_stocks.head()


status  = emasignal.save_EMA_signal_to_db(long_stocks, db_path)
if status:
    print("✅ Database updated successfully")
else:
    print("⚠️ Database Update failed")
# View
ema_df.head()

76 tickers with Close/200ema crossover between 2026-03-02–2026-03-17
34 tickers with 50ema/200ema crossover between 2026-03-02–2026-03-17
✅ Metadata fetched for 106 total stocks
✅ Final signals: 62 long | 68 short
✅ Saved 62 new EMA signal records to SIGNAL_EMA_CROSS
📦 Table now has 4400 total records.
✅ Database updated successfully

,Symbol,signal_1,Date_1,Price_1,7dratio_1,30dratio_1,Vol1,Mom1,signal_2,Date_2,Price_2,7dratio_2,30dratio_2,Vol2,Mom2,currentPrice,Capitalization,MCap,upFrom52wlow,PE,PB,PBXPE,debtToEquity,PS,PricetoCash,EPS,CashperShare,update date,beta,AD,AD_50
0,A2ZINFRA,Price_lt_200ema,2026-03-06,16.0,0.11,2.47,2.47,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,Nano Cap,268.0,0.26,117.0,6.0,663.0,3.54,0.70,55.992647,0.0,0.0,2026-03-17,0.06,NaN,NaN
1,A2ZINFRA,Price_gt_200ema,2026-03-05,17.0,0.40,2.81,2.81,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,Nano Cap,268.0,0.26,117.0,6.0,663.0,3.54,0.70,55.992647,0.0,0.0,2026-03-17,0.06,NaN,NaN
2,A2ZINFRA,Price_lt_200ema,2026-03-04,16.0,0.37,2.70,2.70,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,Nano Cap,268.0,0.26,117.0,6.0,663.0,3.54,0.70,55.992647,0.0,0.0,2026-03-17,0.06,NaN,NaN
4,AADHARHFC,Price_gt_200ema,2026-03-09,482.0,2.30,1.37,2.30,-2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,476.0,Large Cap,20680.0,0.52,20.0,3.0,59.0,2.55,9.64,11.500628,24.0,41.0,2026-03-17,0.00,NaN,NaN
6,ABINFRA,Price_lt_200ema,2026-03-12,17.0,2.99,0.47,2.99,-3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,Small Cap,1089.0,0.59,46.0,7.0,323.0,0.58,4.46,25.110457,0.0,1.0,2026-03-17,0.64,NaN,NaN

##### Update the Stock returns table

In [12]:
# Update the signal returns 
# import accumulation_signal as acs

import importlib
import signal_returns as sigret
# importlib.reload(sigret)

# from signal_returns import generate_signal_returns

status, final_returns = sigret.generate_signal_returns(db_path, stock_df)

if status:
    print("✅ Signal returns generation successful!")
    display(final_returns.head())
else:
    print("❌ Signal returns generation failed.")

✅ Total signals loaded: 2495
✅ Total signals after merging: 415015
📦 Existing SIGNAL_RETURNS records: 2822
✅ New unique records found: 215
💾 SIGNAL_RETURNS table updated successfully.
🔒 Database connection closed.
✅ Signal returns generation successful!

,Symbol,Signal_Type,Signal_date,Signal_Price,Signal_Rank,ret_1w,ret_1w_price,ret_1w_date,ret_2w,ret_2w_price,ret_2w_date,ret_1m,ret_1m_price,ret_1m_date,ret_3m,ret_3m_price,ret_3m_date,ret_6m,ret_6m_price,ret_6m_date,ret_1y,ret_1y_price,ret_1y_date,ret_sinceSignal,current_price,current_date,ret_1w_perc,ret_2w_perc,ret_1m_perc,ret_3m_perc,ret_6m_perc,ret_1y_perc,ret_sinceSignal_perc
11,A2ZINFRA,Accumulation Signal,2026-03-06,16.020000,5,-0.56,15.930000,2026-03-13,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,-4.93,15.23,2026-03-17,-0.56,<NA>,<NA>,<NA>,<NA>,<NA>,-4.93
12,AADHARHFC,Death cross,2026-03-02,453.000000,6,6.34,481.700012,2026-03-09,5.13,476.25,2026-03-17,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,5.13,476.25,2026-03-17,6.34,5.13,<NA>,<NA>,<NA>,<NA>,5.13
21,ABB,Golden cross,2026-02-20,5987.000000,2,1.44,6073.000000,2026-02-27,1.25,6062.00,2026-03-06,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,2026-03-17,1.44,1.25,<NA>,<NA>,<NA>,<NA>,<NA>
24,ACMESOLAR,Accumulation Signal,2026-03-16,244.889999,4,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,2026-03-17,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
25,ACMESOLAR,Accumulation Signal,2026-03-13,255.610001,3,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,2026-03-17,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>